import json
import pytest
from unittest.mock import patch, MagicMock

from awx.api.versioning import reverse
from awx.main.utils.licensing import get_licenser

# Generated by Cursor (claude-4-sonnet)
@pytest.mark.django_db
class TestLicenseCacheClearing:
    """Test cache clearing for LICENSE setting changes"""

    def test_license_from_manifest_clears_cache(self, admin_user, post):
        """Test that posting a manifest to /api/v2/config/ clears the LICENSE cache"""
        
        # Mock the licenser and clear_setting_cache
        with patch('awx.api.views.root.get_licenser') as mock_get_licenser, \
             patch('awx.api.views.root.validate_entitlement_manifest') as mock_validate, \
             patch('awx.api.views.root.clear_setting_cache') as mock_clear_cache, \
             patch('django.db.connection.on_commit') as mock_on_commit:
            
            # Set up mock license data
            mock_license_data = {
                'valid_key': True,
                'license_type': 'enterprise',
                'instance_count': 100,
                'subscription_name': 'Test Enterprise License'
            }
            
            # Mock the validation and license processing
            mock_validate.return_value = [{'some': 'manifest_data'}]
            mock_licenser = MagicMock()
            mock_licenser.license_from_manifest.return_value = mock_license_data
            mock_get_licenser.return_value = mock_licenser
            
            # Prepare the request data (base64 encoded manifest)
            manifest_data = {'manifest': 'ZmFrZS1tYW5pZmVzdC1kYXRh'}  # base64 for "fake-manifest-data"
            
            # Make the POST request
            url = reverse('api:api_v2_config_view')
            response = post(url, manifest_data, admin_user, expect=200)
            
            # Verify the response
            assert response.data == mock_license_data
            
            # Verify license_from_manifest was called
            mock_licenser.license_from_manifest.assert_called_once()
            
            # Verify cache clearing was scheduled
            mock_on_commit.assert_called_once()
            call_args = mock_on_commit.call_args[0][0]  # Get the lambda function
            
            # Execute the lambda to verify it calls clear_setting_cache
            call_args()
            mock_clear_cache.delay.assert_called_once_with(['LICENSE'])

    def test_config_delete_clears_cache(self, admin_user, delete):
        """Test that DELETE /api/v2/config/ clears the LICENSE cache"""
        
        with patch('awx.api.views.root.clear_setting_cache') as mock_clear_cache, \
             patch('django.db.connection.on_commit') as mock_on_commit, \
             patch('django.conf.settings') as mock_settings:
            
            # Make the DELETE request
            url = reverse('api:api_v2_config_view')
            response = delete(url, admin_user, expect=204)
            
            # Verify settings.LICENSE was set to empty dict
            assert mock_settings.LICENSE == {}
            
            # Verify cache clearing was scheduled
            mock_on_commit.assert_called_once()
            call_args = mock_on_commit.call_args[0][0]  # Get the lambda function
            
            # Execute the lambda to verify it calls clear_setting_cache
            call_args()
            mock_clear_cache.delay.assert_called_once_with(['LICENSE'])

    def test_attach_view_clears_cache(self, admin_user, post):
        """Test that posting to /api/v2/config/attach/ clears the LICENSE cache"""
        
        with patch('awx.api.views.root.get_licenser') as mock_get_licenser, \
             patch('awx.api.views.root.clear_setting_cache') as mock_clear_cache, \
             patch('django.db.connection.on_commit') as mock_on_commit, \
             patch('django.conf.settings') as mock_settings:
            
            # Set up mock licenser with validated subscriptions
            mock_licenser = MagicMock()
            subscription_data = {
                'subscription_id': 'test-subscription-123',
                'valid_key': False,
                'license_type': 'enterprise',
                'instance_count': 50
            }
            mock_licenser.validate_rh.return_value = [subscription_data]
            mock_get_licenser.return_value = mock_licenser
            
            # Prepare request data
            request_data = {
                'subscriptions_client_id': 'test-client-id',
                'subscriptions_client_secret': 'test-client-secret',
                'subscription_id': 'test-subscription-123'
            }
            
            # Make the POST request
            url = reverse('api:api_v2_attach_view')
            response = post(url, request_data, admin_user, expect=200)
            
            # Verify the response includes valid_key=True
            assert response.data['valid_key'] is True
            assert response.data['subscription_id'] == 'test-subscription-123'
            
            # Verify settings.LICENSE was set
            expected_license = subscription_data.copy()
            expected_license['valid_key'] = True
            assert mock_settings.LICENSE == expected_license
            
            # Verify cache clearing was scheduled
            mock_on_commit.assert_called_once()
            call_args = mock_on_commit.call_args[0][0]  # Get the lambda function
            
            # Execute the lambda to verify it calls clear_setting_cache
            call_args()
            mock_clear_cache.delay.assert_called_once_with(['LICENSE'])

    def test_attach_view_subscription_not_found_no_cache_clear(self, admin_user, post):
        """Test that attach view doesn't clear cache when subscription is not found"""
        
        with patch('awx.api.views.root.get_licenser') as mock_get_licenser, \
             patch('awx.api.views.root.clear_setting_cache') as mock_clear_cache, \
             patch('django.db.connection.on_commit') as mock_on_commit:
            
            # Set up mock licenser with different subscription
            mock_licenser = MagicMock()
            subscription_data = {
                'subscription_id': 'different-subscription-456',  # Different ID
                'valid_key': False,
                'license_type': 'enterprise'
            }
            mock_licenser.validate_rh.return_value = [subscription_data]
            mock_get_licenser.return_value = mock_licenser
            
            # Request data with non-matching subscription ID
            request_data = {
                'subscriptions_client_id': 'test-client-id',
                'subscriptions_client_secret': 'test-client-secret',
                'subscription_id': 'test-subscription-123'  # This won't match
            }
            
            # Make the POST request
            url = reverse('api:api_v2_attach_view')
            response = post(url, request_data, admin_user, expect=400)
            
            # Verify error response
            assert 'error' in response.data
            
            # Verify cache clearing was NOT called (no matching subscription)
            mock_on_commit.assert_not_called()
            mock_clear_cache.delay.assert_not_called()

    def test_manifest_validation_error_no_cache_clear(self, admin_user, post):
        """Test that config view doesn't clear cache when manifest validation fails"""
        
        with patch('awx.api.views.root.validate_entitlement_manifest') as mock_validate, \
             patch('awx.api.views.root.clear_setting_cache') as mock_clear_cache, \
             patch('django.db.connection.on_commit') as mock_on_commit:
            
            # Mock validation to raise ValueError
            mock_validate.side_effect = ValueError("Invalid manifest")
            
            # Prepare request data
            manifest_data = {'manifest': 'aW52YWxpZC1tYW5pZmVzdA=='}  # base64 for "invalid-manifest"
            
            # Make the POST request
            url = reverse('api:api_v2_config_view')
            response = post(url, manifest_data, admin_user, expect=400)
            
            # Verify error response
            assert response.data['error'] == 'Invalid manifest'
            
            # Verify cache clearing was NOT called (validation failed)
            mock_on_commit.assert_not_called()
            mock_clear_cache.delay.assert_not_called()

    def test_license_processing_error_no_cache_clear(self, admin_user, post):
        """Test that config view doesn't clear cache when license processing fails"""
        
        with patch('awx.api.views.root.get_licenser') as mock_get_licenser, \
             patch('awx.api.views.root.validate_entitlement_manifest') as mock_validate, \
             patch('awx.api.views.root.clear_setting_cache') as mock_clear_cache, \
             patch('django.db.connection.on_commit') as mock_on_commit:
            
            # Mock validation to succeed but license processing to fail
            mock_validate.return_value = [{'some': 'manifest_data'}]
            mock_licenser = MagicMock()
            mock_licenser.license_from_manifest.side_effect = Exception("License processing failed")
            mock_get_licenser.return_value = mock_licenser
            
            # Prepare request data
            manifest_data = {'manifest': 'ZmFrZS1tYW5pZmVzdA=='}  # base64 for "fake-manifest"
            
            # Make the POST request
            url = reverse('api:api_v2_config_view')
            response = post(url, manifest_data, admin_user, expect=400)
            
            # Verify error response
            assert response.data['error'] == 'Invalid License'
            
            # Verify cache clearing was NOT called (license processing failed)
            mock_on_commit.assert_not_called()
            mock_clear_cache.delay.assert_not_called()

    def test_cache_clearing_uses_on_commit(self, admin_user, post):
        """Test that cache clearing is properly deferred using on_commit"""
        
        with patch('awx.api.views.root.get_licenser') as mock_get_licenser, \
             patch('awx.api.views.root.validate_entitlement_manifest') as mock_validate, \
             patch('django.db.connection.on_commit') as mock_on_commit:
            
            # Set up successful license processing
            mock_license_data = {'valid_key': True, 'license_type': 'enterprise'}
            mock_validate.return_value = [{'some': 'manifest_data'}]
            mock_licenser = MagicMock()
            mock_licenser.license_from_manifest.return_value = mock_license_data
            mock_get_licenser.return_value = mock_licenser
            
            # Prepare request data
            manifest_data = {'manifest': 'ZmFrZS1tYW5pZmVzdA=='}
            
            # Make the POST request
            url = reverse('api:api_v2_config_view')
            response = post(url, manifest_data, admin_user, expect=200)
            
            # Verify on_commit was called exactly once with a callable
            mock_on_commit.assert_called_once()
            # Verify the callable is a lambda that calls clear_setting_cache.delay(['LICENSE'])
            # We already tested this in other tests, but this emphasizes the on_commit pattern
            assert callable(mock_on_commit.call_args[0][0]) 