# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-11 16:40
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_v330_blank_start_args'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workflowjobtemplatenode',
            name='workflow_job_template',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='workflow_job_template_nodes', to='main.WorkflowJobTemplate'),
            preserve_default=False,
        ),
    ]
