# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-09 21:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_v330_add_additional_stdout_events'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobtemplate',
            name='custom_virtualenv',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='organization',
            name='custom_virtualenv',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='custom_virtualenv',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
    ]
