# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-21 14:50
from __future__ import unicode_literals

import awx.main.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0026_v330_emitted_events'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='has_active_failures',
        ),
        migrations.RemoveField(
            model_name='inventory',
            name='has_active_failures',
        ),
        migrations.RemoveField(
            model_name='inventory',
            name='has_inventory_sources',
        ),
        migrations.AlterField(
            model_name='group',
            name='groups_with_active_failures',
            field=models.PositiveIntegerField(default=0, editable=False, help_text='DEPRECATED: Number of child groups within this group that have active failures. This field will be removed in a future release.'),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='groups_with_active_failures',
            field=models.PositiveIntegerField(default=0, editable=False, help_text='DEPRECATED: Number of groups in this inventory with active failures. This field will be removed in a future release.'),
        ),
    ]
