# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-16 20:25
from __future__ import unicode_literals

import awx.main.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0028_v330_add_tower_verify'),
    ]

    operations = [
        migrations.AddField(
            model_name='oauth2application',
            name='organization',
            field=models.ForeignKey(help_text='Organization containing this application.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='main.Organization'),
        ),
        migrations.AlterUniqueTogether(
            name='oauth2application',
            unique_together=set([('name', 'organization')]),
        ),
    ]
