# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-06 13:44
from __future__ import unicode_literals

import awx.main.utils.polymorphic
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0031_v330_encrypt_oauth2_secret'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unifiedjob',
            name='instance_group',
            field=models.ForeignKey(blank=True, default=None, help_text='The Instance group the job was run under', null=True, on_delete=awx.main.utils.polymorphic.SET_NULL, to='main.InstanceGroup'),
        ),
    ]
