# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-17 18:36
from __future__ import unicode_literals

from django.db import migrations, models

# TODO: Squash all of these migrations with '0024_v330_add_oauth_activity_stream_registrar'

class Migration(migrations.Migration):

    dependencies = [
        ('main', '0034_v330_delete_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oauth2accesstoken',
            name='scope',
            field=models.TextField(blank=True, default='write', help_text="Allowed scopes, further restricts user's permissions. Must be a simple space-separated string with allowed scopes ['read', 'write']."),
        ),
    ]
