# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-05-23 20:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('main', '0038_v330_add_deleted_activitystream_actor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobtemplate',
            name='custom_virtualenv',
            field=models.CharField(
                blank=True, default=None, help_text='Local absolute file path containing a custom Python virtualenv to use', max_length=100, null=True
            ),
        ),
        migrations.AlterField(
            model_name='organization',
            name='custom_virtualenv',
            field=models.CharField(
                blank=True, default=None, help_text='Local absolute file path containing a custom Python virtualenv to use', max_length=100, null=True
            ),
        ),
        migrations.AlterField(
            model_name='project',
            name='custom_virtualenv',
            field=models.CharField(
                blank=True, default=None, help_text='Local absolute file path containing a custom Python virtualenv to use', max_length=100, null=True
            ),
        ),
    ]
