# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-06-14 17:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0041_v330_update_oauth_refreshtoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='instance',
            name='system_hostname',
            field=models.CharField(default=b'', max_length=255, unique=True),
        ),
    ]
