# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-07-09 21:07
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0042_v330_org_member_role_deparent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='timeout',
            field=models.PositiveIntegerField(blank=True, default=0, help_text='The amount of time (in seconds) to run before the task is canceled.'),
        ),
        migrations.AlterField(
            model_name='jobtemplate',
            name='timeout',
            field=models.PositiveIntegerField(blank=True, default=0, help_text='The amount of time (in seconds) to run before the task is canceled.'),
        ),
    ]
