# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-07-10 14:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0042_v330_org_member_role_deparent'),
    ]

    operations = [
        migrations.AddField(
            model_name='oauth2accesstoken',
            name='modified',
            field=models.DateTimeField(editable=False, auto_now=True),
        ),
    ]
