# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-07-25 17:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0044_v330_add_inventory_update_inventory'),
    ]

    operations = [
        migrations.AddField(
            model_name='instance',
            name='managed_by_policy',
            field=models.BooleanField(default=True),
        )
    ]
