# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-07-25 20:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0046_v330_remove_client_credentials_grant'),
    ]

    operations = [
        migrations.AddField(
            model_name='activitystream',
            name='instance',
            field=models.ManyToManyField(blank=True, to='main.Instance'),
        ),
    ]
