# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-08-14 13:43
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0047_v330_activitystream_instance'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobtemplate',
            name='job_shard_count',
            field=models.IntegerField(blank=True,
                                      default=0,
                                      help_text='The number of jobs to split into at runtime. Will cause the Job Template to launch a workflow.'),
        ),
    ]
