# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-09-13 15:55
from __future__ import unicode_literals

import awx.main.utils.polymorphic
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0047_v330_activitystream_instance'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobtemplate',
            name='job_shard_count',
            field=models.IntegerField(blank=True, default=0, help_text='The number of jobs to split into at runtime. Will cause the Job Template to launch a workflow if value is non-zero.'),
        ),
        migrations.AddField(
            model_name='workflowjob',
            name='job_template',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sharded_jobs', to='main.JobTemplate'),
        ),
        migrations.AlterField(
            model_name='unifiedjob',
            name='unified_job_template',
            field=models.ForeignKey(default=None, editable=False, null=True, on_delete=awx.main.utils.polymorphic.SET_NULL, related_name='unifiedjob_unified_jobs', to='main.UnifiedJobTemplate'),
        ),
        migrations.AddField(
            model_name='job',
            name='internal_limit',
            field=models.CharField(default=b'', editable=False, max_length=1024),
        ),
    ]
