# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-09-10 17:41
from __future__ import unicode_literals

import awx.main.utils.polymorphic
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0049_v340_add_job_template'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unifiedjob',
            name='unified_job_template',
            field=models.ForeignKey(default=None, editable=False, null=True, on_delete=awx.main.utils.polymorphic.SET_NULL, related_name='unifiedjob_unified_jobs', to='main.UnifiedJobTemplate'),
        ),
    ]
