# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-05-18 17:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0051_v340_job_slicing'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='scm_delete_on_next_update',
        ),
    ]
