# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-07 13:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0052_v340_remove_project_scm_delete_on_next_update'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskRescheduleFlag',
            fields=[
                ('name', models.CharField(max_length=512, primary_key=True, serialize=False, unique=True)),
            ],
        ),
    ]
