# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-01-22 22:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0055_v340_add_grafana_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventoryupdate',
            name='custom_virtualenv',
            field=models.CharField(blank=True, default=None, help_text='Local absolute file path containing a custom Python virtualenv to use', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='custom_virtualenv',
            field=models.CharField(blank=True, default=None, help_text='Local absolute file path containing a custom Python virtualenv to use', max_length=100, null=True),
        ),
    ]
