# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-01-31 20:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0056_v350_custom_venv_history'),
    ]

    operations = [
        migrations.AddField(
            model_name='adhoccommand',
            name='host_impact',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='host_impact',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='unifiedjob',
            name='controller_node',
            field=models.TextField(blank=True, db_index=True, default='', editable=False, help_text='The instance that managed the isolated execution environment.'),
        ),
        migrations.AlterField(
            model_name='unifiedjob',
            name='execution_node',
            field=models.TextField(blank=True, db_index=True, default='', editable=False, help_text='The node the job executed on.'),
        ),
        migrations.AlterField(
            model_name='unifiedjob',
            name='status',
            field=models.CharField(choices=[('new', 'New'), ('pending', 'Pending'), ('waiting', 'Waiting'), ('running', 'Running'), ('successful', 'Successful'), ('failed', 'Failed'), ('error', 'Error'), ('canceled', 'Canceled')], db_index=True, default='new', editable=False, max_length=20),
        ),
    ]
