# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-01-29 19:56
from __future__ import unicode_literals

from django.db import migrations

# AWX
from awx.main.migrations import _credentialtypes as credentialtypes


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0056_v350_custom_venv_history'),
    ]

    operations = [
        migrations.RunPython(credentialtypes.remove_become_methods),
    ]
