# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-02-05 18:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0057_v350_remove_become_method_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='limit',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='jobtemplate',
            name='limit',
            field=models.TextField(blank=True, default=''),
        ),
    ]
