# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-02-06 20:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0058_v350_remove_limit_limit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adhoccommandevent',
            name='changed',
        ),
        migrations.RemoveField(
            model_name='adhoccommandevent',
            name='failed',
        ),
        migrations.RemoveField(
            model_name='jobevent',
            name='changed',
        ),
        migrations.RemoveField(
            model_name='jobevent',
            name='failed',
        ),
        migrations.RemoveField(
            model_name='projectupdateevent',
            name='changed',
        ),
        migrations.RemoveField(
            model_name='projectupdateevent',
            name='failed',
        ),
    ]
