# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-02-13 13:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0058_v350_remove_limit_limit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adhoccommand',
            name='limit',
            field=models.TextField(blank=True, default=''),
        ),
    ]
