# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-02-13 17:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0059_v350_remove_adhoc_limit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='name',
            field=models.CharField(max_length=512),
        ),
        migrations.AlterUniqueTogether(
            name='schedule',
            unique_together=set([('unified_job_template', 'name')]),
        ),
    ]
