# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-02-21 17:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0061_v350_track_native_credentialtype_source'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='groups_with_active_failures',
        ),
        migrations.RemoveField(
            model_name='group',
            name='has_active_failures',
        ),
        migrations.RemoveField(
            model_name='group',
            name='has_inventory_sources',
        ),
        migrations.RemoveField(
            model_name='group',
            name='hosts_with_active_failures',
        ),
        migrations.RemoveField(
            model_name='group',
            name='total_groups',
        ),
        migrations.RemoveField(
            model_name='group',
            name='total_hosts',
        ),
        migrations.RemoveField(
            model_name='host',
            name='has_active_failures',
        ),
        migrations.RemoveField(
            model_name='host',
            name='has_inventory_sources',
        ),
    ]
