# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-02-15 20:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0062_v350_new_playbook_stats'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventoryupdate',
            name='org_host_limit_error',
            field=models.BooleanField(default=False, editable=False),
        ),
        migrations.AddField(
            model_name='organization',
            name='max_hosts',
            field=models.PositiveIntegerField(blank=True, default=0, help_text='Maximum number of hosts allowed to be managed by this organization.'),
        ),
    ]
