# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-03-14 12:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0063_v350_org_host_limits'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='runner_job_ident',
            field=models.TextField(blank=True, default=''),
        ),
    ]
