# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-03-29 16:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0064_v350_analytics_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unifiedjob',
            name='status',
            field=models.CharField(choices=[('new', 'New'), ('pending', 'Pending'), ('waiting', 'Waiting'), ('running', 'Running'), ('successful', 'Successful'), ('failed', 'Failed'), ('error', 'Error'), ('canceled', 'Canceled')], db_index=True, default='new', editable=False, max_length=20),
        ),
    ]
