# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-03-28 17:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0065_v350_index_job_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventorysource',
            name='custom_virtualenv',
            field=models.CharField(blank=True, default=None, help_text='Local absolute file path containing a custom Python virtualenv to use', max_length=100, null=True),
        ),
    ]
