# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-04-03 05:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0067_v350_credential_plugins'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobevent',
            name='created',
            field=models.DateTimeField(db_index=True, default=None, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='projectupdateevent',
            name='created',
            field=models.DateTimeField(db_index=True, default=None, editable=False, null=True),
        ),
    ]
