# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-04-03 01:23
from __future__ import unicode_literals

import awx.main.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0069_v350_generate_unique_install_uuid'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobevent',
            name='profiling_data',
            field=awx.main.fields.JSONField(blank=True, default={}),
        ),
        migrations.AddField(
            model_name='projectupdateevent',
            name='profiling_data',
            field=awx.main.fields.JSONField(blank=True, default={}),
        ),
    ]
