# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-04-10 12:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0070_v350_gce_instance_id'),
    ]

    operations = [
        migrations.AlterIndexTogether(
            name='fact',
            index_together=set([]),
        ),
        migrations.RemoveField(
            model_name='fact',
            name='host',
        ),
        migrations.DeleteModel(
            name='Fact',
        ),
    ]
