# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-04-18 19:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0071_v350_remove_system_tracking'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='groups_with_active_failures',
            field=models.PositiveIntegerField(default=0, editable=False, help_text='This field is deprecated and will be removed in a future release. Number of child groups within this group that have active failures.'),
        ),
        migrations.AlterField(
            model_name='group',
            name='has_active_failures',
            field=models.BooleanField(default=False, editable=False, help_text='This field is deprecated and will be removed in a future release. Flag indicating whether this group has any hosts with active failures.'),
        ),
        migrations.AlterField(
            model_name='group',
            name='has_inventory_sources',
            field=models.BooleanField(default=False, editable=False, help_text='This field is deprecated and will be removed in a future release. Flag indicating whether this group was created/updated from any external inventory sources.'),
        ),
        migrations.AlterField(
            model_name='group',
            name='hosts_with_active_failures',
            field=models.PositiveIntegerField(default=0, editable=False, help_text='This field is deprecated and will be removed in a future release. Number of hosts in this group with active failures.'),
        ),
        migrations.AlterField(
            model_name='group',
            name='total_groups',
            field=models.PositiveIntegerField(default=0, editable=False, help_text='This field is deprecated and will be removed in a future release. Total number of child groups contained within this group.'),
        ),
        migrations.AlterField(
            model_name='group',
            name='total_hosts',
            field=models.PositiveIntegerField(default=0, editable=False, help_text='This field is deprecated and will be removed in a future release. Total number of hosts directly or indirectly in this group.'),
        ),
        migrations.AlterField(
            model_name='host',
            name='has_active_failures',
            field=models.BooleanField(default=False, editable=False, help_text='This field is deprecated and will be removed in a future release. Flag indicating whether the last job failed for this host.'),
        ),
        migrations.AlterField(
            model_name='host',
            name='has_inventory_sources',
            field=models.BooleanField(default=False, editable=False, help_text='This field is deprecated and will be removed in a future release. Flag indicating whether this host was created/updated from any external inventory sources.'),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='groups_with_active_failures',
            field=models.PositiveIntegerField(default=0, editable=False, help_text='This field is deprecated and will be removed in a future release. Number of groups in this inventory with active failures.'),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='has_active_failures',
            field=models.BooleanField(default=False, editable=False, help_text='This field is deprecated and will be removed in a future release. Flag indicating whether any hosts in this inventory have failed.'),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='has_inventory_sources',
            field=models.BooleanField(default=False, editable=False, help_text='This field is deprecated and will be removed in a future release. Flag indicating whether this inventory has any external inventory sources.'),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='hosts_with_active_failures',
            field=models.PositiveIntegerField(default=0, editable=False, help_text='This field is deprecated and will be removed in a future release. Number of hosts in this inventory with active failures.'),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='total_groups',
            field=models.PositiveIntegerField(default=0, editable=False, help_text='This field is deprecated and will be removed in a future release. Total number of groups in this inventory.'),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='total_hosts',
            field=models.PositiveIntegerField(default=0, editable=False, help_text='This field is deprecated and will be removed in a future release. Total number of hosts in this inventory.'),
        ),
    ]
