# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-06 15:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0074_v360_migrate_instance_group_relations'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventory',
            name='instance_groups',
        ),
        migrations.RemoveField(
            model_name='organization',
            name='instance_groups',
        ),
        migrations.RemoveField(
            model_name='unifiedjobtemplate',
            name='instance_groups',
        ),
    ]
