# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-06 15:20
from __future__ import unicode_literals

from django.db import migrations, models
from awx.main.fields import OrderedManyToManyField


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0075_v360_remove_old_instance_group_relations'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory',
            name='instance_groups',
            field=OrderedManyToManyField(blank=True, through='main.InventoryInstanceGroupMembership', to='main.InstanceGroup'),
        ),
        migrations.AddField(
            model_name='organization',
            name='instance_groups',
            field=OrderedManyToManyField(blank=True, through='main.OrganizationInstanceGroupMembership', to='main.InstanceGroup'),
        ),
        migrations.AddField(
            model_name='unifiedjobtemplate',
            name='instance_groups',
            field=OrderedManyToManyField(blank=True, through='main.UnifiedJobTemplateInstanceGroupMembership', to='main.InstanceGroup'),
        ),
    ]
