# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-14 14:51
from __future__ import unicode_literals

from django.db import migrations, models

from awx.main.utils.common import set_current_apps


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0079_v360_rm_implicit_oauth2_apps'),
    ]

    operations = [
        migrations.RunPython(migrations.RunPython.noop, lambda apps, schema_editor: set_current_apps(apps)),
        migrations.RemoveField(
            model_name='joborigin',
            name='instance',
        ),
        migrations.RemoveField(
            model_name='joborigin',
            name='unified_job',
        ),
        migrations.AddField(
            model_name='activitystream',
            name='action_node',
            field=models.CharField(blank=True, default='', editable=False, help_text='The cluster node the activity took place on.', max_length=512),
        ),
        migrations.DeleteModel(
            name='JobOrigin',
        ),
        migrations.RunPython(lambda apps, schema_editor: set_current_apps(apps), migrations.RunPython.noop)
    ]
