# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-30 20:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0080_v360_replace_job_origin'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='notification_templates_started',
            field=models.ManyToManyField(blank=True, related_name='organization_notification_templates_for_started', to='main.NotificationTemplate'),
        ),
        migrations.AddField(
            model_name='unifiedjobtemplate',
            name='notification_templates_started',
            field=models.ManyToManyField(blank=True, related_name='unifiedjobtemplate_notification_templates_for_started', to='main.NotificationTemplate'),
        ),
#        migrations.RunPython() stuff goes in here
        migrations.RemoveField(
            model_name='organization',
            name='notification_templates_any',
        ),
        migrations.RemoveField(
            model_name='unifiedjobtemplate',
            name='notification_templates_any',
        ),
    ]
