# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-07-03 14:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0081_v360_notify_on_start'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkflowApproval',
            fields=[
                ('unifiedjob_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='main.UnifiedJob')),
            ],
            options={
                'manager_inheritance_from_future': True,
            },
            bases=('main.unifiedjob',),
        ),
        migrations.CreateModel(
            name='WorkflowApprovalTemplate',
            fields=[
                ('unifiedjobtemplate_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='main.UnifiedJobTemplate')),
            ],
            options={
                'manager_inheritance_from_future': True,
            },
            bases=('main.unifiedjobtemplate',),
        ),
        migrations.AddField(
            model_name='workflowapproval',
            name='workflow_approval_template',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approvals', to='main.WorkflowApprovalTemplate'),
        ),
    ]
