# Generated by Django 2.2.4 on 2019-08-07 19:56

import awx.main.fields
from django.db import migrations, models
import django.db.models.deletion

from awx.main.migrations._rbac import rebuild_role_parentage, migrate_ujt_organization


NULL_PARENTS = [
    # remove old field from job template role parentage
    # this is done so the model state is consistent in next step
    migrations.AlterField(
        model_name='jobtemplate',
        name='admin_role',
        field=awx.main.fields.ImplicitRoleField(editable=False, null='True', on_delete=django.db.models.deletion.CASCADE, parent_role=[], related_name='+', to='main.Role'),
    ),
    migrations.AlterField(
        model_name='jobtemplate',
        name='execute_role',
        field=awx.main.fields.ImplicitRoleField(editable=False, null='True', on_delete=django.db.models.deletion.CASCADE, parent_role=['admin_role'], related_name='+', to='main.Role'),
    ),
    migrations.AlterField(
        model_name='jobtemplate',
        name='read_role',
        field=awx.main.fields.ImplicitRoleField(editable=False, null='True', on_delete=django.db.models.deletion.CASCADE, parent_role=['execute_role', 'admin_role'], related_name='+', to='main.Role'),
    ),
    # same for workflow job templates
    # organization field moves, but does not move in relative name
    # so this is undone a little later, this is only for state consistency
    migrations.AlterField(
        model_name='workflowjobtemplate',
        name='admin_role',
        field=awx.main.fields.ImplicitRoleField(editable=False, null='True', on_delete=django.db.models.deletion.CASCADE, parent_role=[], related_name='+', to='main.Role'),
    ),
    migrations.AlterField(
        model_name='workflowjobtemplate',
        name='execute_role',
        field=awx.main.fields.ImplicitRoleField(editable=False, null='True', on_delete=django.db.models.deletion.CASCADE, parent_role=[], related_name='+', to='main.Role'),
    ),
    migrations.AlterField(
        model_name='workflowjobtemplate',
        name='read_role',
        field=awx.main.fields.ImplicitRoleField(editable=False, null='True', on_delete=django.db.models.deletion.CASCADE, parent_role=[], related_name='+', to='main.Role'),
    ),
    # same for projects
    migrations.AlterField(
        model_name='project',
        name='admin_role',
        field=awx.main.fields.ImplicitRoleField(editable=False, null='True', on_delete=django.db.models.deletion.CASCADE, parent_role=[], related_name='+', to='main.Role'),
    ),
    migrations.AlterField(
        model_name='project',
        name='update_role',
        field=awx.main.fields.ImplicitRoleField(editable=False, null='True', on_delete=django.db.models.deletion.CASCADE, parent_role=[], related_name='+', to='main.Role'),
    ),
    migrations.AlterField(
        model_name='project',
        name='read_role',
        field=awx.main.fields.ImplicitRoleField(editable=False, null='True', on_delete=django.db.models.deletion.CASCADE, parent_role=[], related_name='+', to='main.Role'),
    ),
    migrations.AlterField(
        model_name='project',
        name='use_role',
        field=awx.main.fields.ImplicitRoleField(editable=False, null='True', on_delete=django.db.models.deletion.CASCADE, parent_role=[], related_name='+', to='main.Role'),
    ),
]


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0082_v360_webhook_http_method'),
    ]

    operations = [
        # backwards parents and ancestors caching
        migrations.RunPython(migrations.RunPython.noop, rebuild_role_parentage),

        # before adding the new fields, rename the old fields
        # migrations.AlterField(
        #     model_name='workflowjobtemplate',
        #     name='organization',
        #     field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='workflows', to='main.Organization', db_column='organization'),
        # ),
        # migrations.RenameField(
        #     model_name='workflowjobtemplate',
        #     old_name='organization',
        #     new_name='tmp_organization',
        # ),
        # migrations.AlterField(
        #     model_name='project',
        #     name='organization',
        #     field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='main.Organization', db_column='organization'),
        # ),
        # migrations.RenameField(
        #     model_name='project',
        #     old_name='organization',
        #     new_name='tmp_organization',
        # ),
        # add new organization field for JT and all other unified jobs
        migrations.AddField(
            model_name='unifiedjob',
            name='organization',
            field=models.ForeignKey(blank=True, help_text='The organization used to determine access to this unified job.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='unifiedjobs', to='main.Organization'),
        ),
        migrations.AddField(
            model_name='unifiedjobtemplate',
            name='organization',
            field=models.ForeignKey(blank=True, help_text='The organization used to determine access to this template.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='unifiedjobtemplates', to='main.Organization'),
        ),
        # add new field to the parentage of job template roles
        migrations.AlterField(
            model_name='jobtemplate',
            name='admin_role',
            field=awx.main.fields.ImplicitRoleField(editable=False, null='True', on_delete=django.db.models.deletion.CASCADE, parent_role=['organization.job_template_admin_role'], related_name='+', to='main.Role'),
        ),
        migrations.AlterField(
            model_name='jobtemplate',
            name='execute_role',
            field=awx.main.fields.ImplicitRoleField(editable=False, null='True', on_delete=django.db.models.deletion.CASCADE, parent_role=['admin_role', 'organization.execute_role'], related_name='+', to='main.Role'),
        ),
        migrations.AlterField(
            model_name='jobtemplate',
            name='read_role',
            field=awx.main.fields.ImplicitRoleField(editable=False, null='True', on_delete=django.db.models.deletion.CASCADE, parent_role=['organization.auditor_role', 'execute_role', 'admin_role'], related_name='+', to='main.Role'),
        ),
        migrations.RunPython(migrate_ujt_organization, migrations.RunPython.noop),
        # Re-compute the role parents and ancestors caching
        # this may be a no-op because field post_save hooks from migrate_jt_organization
        migrations.RunPython(rebuild_role_parentage, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name='project',
            name='organization',
        ),
        migrations.RemoveField(
            model_name='workflowjobtemplate',
            name='organization',
        ),
    ]
