# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-06-10 16:56
from __future__ import unicode_literals

from django.db import migrations, models

import awx.main.fields


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0082_v360_webhook_http_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificationtemplate',
            name='messages',
            field=awx.main.fields.JSONField(default=dict,
                                            help_text='Optional custom messages for notification template.',
                                            null=True,
                                            blank=True),
        ),
    ]
