# Generated by Django 2.2.4 on 2019-08-16 13:22

from django.db import migrations, models

import awx

class Migration(migrations.Migration):

    dependencies = [
        ('main', '0083_v360_job_branch_override'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oauth2accesstoken',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
    ]
