# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-06-10 16:56
from __future__ import unicode_literals

from django.db import migrations, models

import awx.main.fields
import awx.main.models.notifications


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0084_v360_token_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificationtemplate',
            name='messages',
            field=awx.main.fields.JSONField(default=awx.main.models.notifications.NotificationTemplate.default_messages,
                                            help_text='Optional custom messages for notification template.',
                                            null=True,
                                            blank=True),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('email', 'Email'), ('grafana', 'Grafana'), ('hipchat', 'HipChat'), ('irc', 'IRC'), ('mattermost', 'Mattermost'), ('pagerduty', 'Pagerduty'), ('rocketchat', 'Rocket.Chat'), ('slack', 'Slack'), ('twilio', 'Twilio'), ('webhook', 'Webhook')], max_length=32),
        ),
        migrations.AlterField(
            model_name='notificationtemplate',
            name='notification_type',
            field=models.CharField(choices=[('email', 'Email'), ('grafana', 'Grafana'), ('hipchat', 'HipChat'), ('irc', 'IRC'), ('mattermost', 'Mattermost'), ('pagerduty', 'Pagerduty'), ('rocketchat', 'Rocket.Chat'), ('slack', 'Slack'), ('twilio', 'Twilio'), ('webhook', 'Webhook')], max_length=32),
        ),
    ]
