# Generated by Django 2.2.4 on 2019-08-19 18:26

import awx.main.fields
from django.db import migrations
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0084_v360_token_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='read_role',
            field=awx.main.fields.ImplicitRoleField(editable=False, null='True', on_delete=django.db.models.deletion.CASCADE, parent_role=['organization.auditor_role', 'organization.member_role', 'member_role'], related_name='+', to='main.Role'),
        ),
    ]
