# Generated by Django 2.2.4 on 2019-08-19 15:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0084_v360_token_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='instancegroup',
            name='credential',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='instancegroups', to='main.Credential'),
        ),
        migrations.AddField(
            model_name='instancegroup',
            name='pod_spec_override',
            field=models.TextField(blank=True, default=''),
        ),
    ]
