# Generated by Django 2.2.4 on 2019-10-16 19:51

from django.db import migrations


def update_cyberark_aim_name(apps, schema_editor):
    apps.get_model('main', 'CredentialType').objects.filter(namespace='aim').update(
        name='CyberArk AIM Central Credential Provider Lookup'
    )


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0097_v360_workflowapproval_approved_or_denied_by'),
    ]

    operations = [
        migrations.RunPython(update_cyberark_aim_name)
    ]
