# Generated by Django 2.2.4 on 2019-12-19 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0100_v370_projectupdate_job_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='unifiedjob',
            name='canceled_on',
            field=models.DateTimeField(db_index=True, default=None, editable=False, help_text='The date and time the job was canceled.', null=True),
        ),
    ]
