# Generated by Django 2.2.4 on 2020-01-07 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0100_v370_projectupdate_job_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='workflowjobnode',
            name='all_parents_must_converge',
            field=models.BooleanField(default=False, help_text='If enabled then the node will only run if all of the parent nodes have met the criteria to reach this node', verbose_name='self'),
        ),
        migrations.AddField(
            model_name='workflowjobtemplatenode',
            name='all_parents_must_converge',
            field=models.BooleanField(default=False, help_text='If enabled then the node will only run if all of the parent nodes have met the criteria to reach this node', verbose_name='self'),
        ),
    ]
