# Generated by Django 2.2.4 on 2019-11-25 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0101_v370_generate_new_uuids_for_iso_nodes'),
    ]

    operations = [
        migrations.AddField(
            model_name='unifiedjob',
            name='canceled_on',
            field=models.DateTimeField(db_index=True, default=None, editable=False, help_text='The date and time when the cancel request was sent.', null=True),
        ),
    ]
