# Generated by Django 2.2.8 on 2020-01-15 15:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0102_v370_unifiedjob_canceled'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobevent',
            name='parent',
        ),
    ]
