# Generated by Django 2.2.8 on 2020-01-27 12:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0105_v370_remove_jobevent_parent_and_hosts'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventory',
            name='groups_with_active_failures',
        ),
    ]
