# Generated by Django 2.2.4 on 2020-01-08 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0106_v370_remove_inventory_groups_with_active_failures'),
    ]

    operations = [
        migrations.AddField(
            model_name='workflowjobnode',
            name='all_parents_must_converge',
            field=models.BooleanField(default=False, help_text='If enabled then the node will only run if all of the parent nodes have met the criteria to reach this node'),
        ),
        migrations.AddField(
            model_name='workflowjobtemplatenode',
            name='all_parents_must_converge',
            field=models.BooleanField(default=False, help_text='If enabled then the node will only run if all of the parent nodes have met the criteria to reach this node'),
        ),
    ]
