# Generated by Django 2.2.8 on 2020-02-07 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0107_v370_workflow_convergence_api_toggle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='webhook_service',
            field=models.CharField(blank=True, choices=[('github', 'GitHub'), ('gitlab', 'GitLab'), ('gitea', 'Gitea')], help_text='Service that webhook requests will be accepted from', max_length=16),
        ),
        migrations.AlterField(
            model_name='jobtemplate',
            name='webhook_service',
            field=models.CharField(blank=True, choices=[('github', 'GitHub'), ('gitlab', 'GitLab'), ('gitea', 'Gitea')], help_text='Service that webhook requests will be accepted from', max_length=16),
        ),
        migrations.AlterField(
            model_name='workflowjob',
            name='webhook_service',
            field=models.CharField(blank=True, choices=[('github', 'GitHub'), ('gitlab', 'GitLab'), ('gitea', 'Gitea')], help_text='Service that webhook requests will be accepted from', max_length=16),
        ),
        migrations.AlterField(
            model_name='workflowjobtemplate',
            name='webhook_service',
            field=models.CharField(blank=True, choices=[('github', 'GitHub'), ('gitlab', 'GitLab'), ('gitea', 'Gitea')], help_text='Service that webhook requests will be accepted from', max_length=16),
        ),
    ]
