# Generated by Django 2.2.8 on 2020-03-06 14:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0108_v370_unifiedjob_dependencies_processed'),
    ]

    operations = [
        migrations.AddField(
            model_name='workflowjobnode',
            name='template_node',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='job_nodes', to='main.WorkflowJobTemplateNode'),
        ),
    ]
