# Generated by Django 2.2.11 on 2020-05-04 02:26

import awx.main.utils.polymorphic
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0115_v370_schedule_set_null'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='sync_assets',
            field=models.BooleanField(default=False, editable=True, help_text='When syncing the assets, load Tower assets from the projects assets folder.'),
        ),
    ]
