# Generated by Django 2.2.11 on 2020-07-20 19:56

import logging
import json
import yaml

from django.db import migrations

from awx.main.models.base import VarsDictProperty

from ._inventory_source_vars import FrozenInjectors


logger = logging.getLogger('awx.main.migrations')
BACKUP_FILENAME = '/tmp/tower_migration_inventory_source_vars.json'


def _get_inventory_sources(InventorySource):
    return InventorySource.objects.filter(source__in=['ec2', 'gce', 'azure_rm', 'vmware', 'satellite6', 'openstack', 'rhv', 'tower'])


def inventory_source_vars_forward(apps, schema_editor):
    InventorySource = apps.get_model("main", "InventorySource")
    '''
    The Django app registry does not keep track of model inheritance. The
    source_vars_dict property comes from InventorySourceOptions via inheritance.
    This adds that property. Luckily, other properteries and functionality from
    InventorySourceOptions is not needed by the injector logic.
    '''
    setattr(InventorySource, 'source_vars_dict', VarsDictProperty('source_vars'))
    source_vars_backup = dict()

    for inv_source_obj in _get_inventory_sources(InventorySource):

        if inv_source_obj.source in FrozenInjectors:
            source_vars_backup[inv_source_obj.id] = dict(inv_source_obj.source_vars_dict)
            with open(BACKUP_FILENAME, 'w') as fh:
                json.dump(source_vars_backup, fh)

            injector = FrozenInjectors[inv_source_obj.source]()
            new_inv_source_vars = injector.inventory_as_dict(inv_source_obj, None)
            inv_source_obj.source_vars = yaml.dump(new_inv_source_vars)
            inv_source_obj.save()


def inventory_source_vars_backward(apps, schema_editor):
    InventorySource = apps.get_model("main", "InventorySource")
    try:
        with open(BACKUP_FILENAME, 'r') as fh:
            source_vars_backup = json.load(fh)
    except FileNotFoundError:
        print(f"Rollback file not found {BACKUP_FILENAME}")
        return

    for inv_source_obj in _get_inventory_sources(InventorySource):
        if inv_source_obj.id in source_vars_backup:
            inv_source_obj.source_vars = source_vars_backup[inv_source_obj.id]
            inv_source_obj.save()


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0117_v400_remove_cloudforms_inventory'),
    ]

    operations = [
        migrations.RunPython(inventory_source_vars_forward, inventory_source_vars_backward,),
        migrations.RemoveField(
            model_name='inventorysource',
            name='group_by',
        ),
        migrations.RemoveField(
            model_name='inventoryupdate',
            name='group_by',
        ),
        migrations.RemoveField(
            model_name='inventorysource',
            name='instance_filters',
        ),
        migrations.RemoveField(
            model_name='inventoryupdate',
            name='instance_filters',
        ),
        migrations.RemoveField(
            model_name='inventorysource',
            name='source_regions',
        ),
        migrations.RemoveField(
            model_name='inventoryupdate',
            name='source_regions',
        ),
    ]
