# Generated by Django 2.2.11 on 2020-06-04 03:55

import awx.main.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0117_v400_remove_cloudforms_inventory'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='invalid_playbook_files',
            field=awx.main.fields.JSONField(blank=True, default=[], editable=False, help_text='List of invalid playbooks found in the project', verbose_name='Invalid Playbook Files'),
        ),
        migrations.AddField(
            model_name='project',
            name='non_yaml_playbook_files',
            field=awx.main.fields.JSONField(blank=True, default=[], editable=False, help_text='List of non yaml playbooks found in the project', verbose_name='Non Yaml Playbook Files'),
        ),
    ]
