# Generated by Django 2.2.11 on 2020-07-24 17:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0120_galaxy_credentials'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TowerAnalyticsState',
        ),
    ]
