# Generated by Django 2.2.11 on 2020-09-22 14:47

import awx.main.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0122_execution_environments'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='executionenvironment',
            options={'ordering': ('-created',)},
        ),
        migrations.AddField(
            model_name='organization',
            name='execution_environment_admin_role',
            field=awx.main.fields.ImplicitRoleField(editable=False, null='True', on_delete=django.db.models.deletion.CASCADE, parent_role='admin_role', related_name='+', to='main.Role'),
            preserve_default='True',
        ),
        migrations.AddField(
            model_name='project',
            name='default_environment',
            field=models.ForeignKey(blank=True, default=None, help_text='The default execution environment for jobs run using this project.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='main.ExecutionEnvironment'),
        ),
    ]
