# Generated by Django 2.2.16 on 2020-11-10 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0123_execution_environments'),
    ]

    operations = [
        migrations.AddField(
            model_name='unifiedjob',
            name='receptor_work_id',
            field=models.CharField(blank=True, default='', editable=False, max_length=32),
        ),
    ]
