# Generated by Django 2.2.16 on 2021-01-13 20:37

import awx.main.fields
import awx.main.models.notifications
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0123_drop_hg_support'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='sync_assets',
            field=models.BooleanField(default=False, editable=True, help_text='When syncing the assets, load Tower assets from the projects assets folder.'),
        ),
    ]
