# Generated by Django 2.2.16 on 2021-01-26 17:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0124_v410_sync_assets'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='project_export',
            field=models.ForeignKey(blank=True, default=None, help_text='The SCM Export task used to send Job Templates to the SCM', null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.ProjectExport'),
        ),
    ]
