# Generated by Django 2.2.16 on 2021-01-14 12:09

import awx.main.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0126_v410_export_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='activitystream',
            name='project_export',
            field=models.ManyToManyField(blank=True, to='main.ProjectExport'),
        ),
        migrations.AddField(
            model_name='projectexportevent',
            name='parent_uuid',
            field=models.CharField(default='', editable=False, max_length=1024),
        ),
        migrations.AlterField(
            model_name='project',
            name='read_role',
            field=awx.main.fields.ImplicitRoleField(editable=False, null='True', on_delete=django.db.models.deletion.CASCADE, parent_role=['organization.auditor_role', 'singleton:system_auditor', 'use_role', 'update_role', 'export_role'], related_name='+', to='main.Role'),
        ),
        migrations.AlterField(
            model_name='projectexport',
            name='scm_revision',
            field=models.CharField(blank=True, default='', editable=False, help_text='The SCM Revision returned by this export for the given project and branch.', max_length=1024, verbose_name='SCM Revision'),
        ),
        migrations.AlterIndexTogether(
            name='projectexportevent',
            index_together={('project_export', 'start_line'), ('project_export', 'end_line'), ('project_export', 'parent_uuid'), ('project_export', 'uuid'), ('project_export', 'event')},
        ),
    ]
