# Generated by Django 2.2.16 on 2021-02-16 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0127_reset_pod_spec_override'),
    ]

    operations = [
        migrations.AlterField(
            model_name='executionenvironment',
            name='pull',
            field=models.CharField(choices=[('always', 'Always pull container before running.'), ('missing', 'No pull option has been selected.'), ('never', 'Never pull container before running.')], default=None, help_text='Pull image before running?', max_length=1024),
        ),
    ]
