# Generated by Django 2.2.16 on 2021-01-21 10:12

import awx.main.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0128_projectexport_commit_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectexport',
            name='job_template_ids',
            field=awx.main.fields.JSONField(blank=True, default=[], editable=False, help_text='List of job tempaltes ids to export', verbose_name='Job Template IDs'),
        ),
        migrations.AddField(
            model_name='projectexport',
            name='workflow_job_template_ids',
            field=awx.main.fields.JSONField(blank=True, default=[], editable=False, help_text='List of workflow job tempaltes ids to export', verbose_name='Workflow Job Template IDs'),
        ),
    ]
