# Generated by Django 2.2.16 on 2021-01-21 10:17

import awx.main.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0129_auto_20210121_1012'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectexport',
            name='job_template_ids',
            field=awx.main.fields.JSONField(default=[], editable=False, help_text='List of job tempaltes ids to export', verbose_name='Job Template IDs'),
        ),
        migrations.AlterField(
            model_name='projectexport',
            name='workflow_job_template_ids',
            field=awx.main.fields.JSONField(default=[], editable=False, help_text='List of workflow job tempaltes ids to export', verbose_name='Workflow Job Template IDs'),
        ),
    ]
