# Generated by Django 2.2.16 on 2021-03-11 16:25

import awx.main.utils.polymorphic
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('main', '0129_unifiedjob_installed_collections'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='default_environment',
            field=models.ForeignKey(
                blank=True,
                default=None,
                help_text='The default execution environment for jobs run by this organization.',
                null=True,
                on_delete=awx.main.utils.polymorphic.SET_NULL,
                related_name='+',
                to='main.ExecutionEnvironment',
            ),
        ),
        migrations.AlterField(
            model_name='project',
            name='default_environment',
            field=models.ForeignKey(
                blank=True,
                default=None,
                help_text='The default execution environment for jobs run using this project.',
                null=True,
                on_delete=awx.main.utils.polymorphic.SET_NULL,
                related_name='+',
                to='main.ExecutionEnvironment',
            ),
        ),
        migrations.AlterField(
            model_name='unifiedjob',
            name='execution_environment',
            field=models.ForeignKey(
                blank=True,
                default=None,
                help_text='The container image to be used for execution.',
                null=True,
                on_delete=awx.main.utils.polymorphic.SET_NULL,
                related_name='unifiedjobs',
                to='main.ExecutionEnvironment',
            ),
        ),
        migrations.AlterField(
            model_name='unifiedjobtemplate',
            name='execution_environment',
            field=models.ForeignKey(
                blank=True,
                default=None,
                help_text='The container image to be used for execution.',
                null=True,
                on_delete=awx.main.utils.polymorphic.SET_NULL,
                related_name='unifiedjobtemplates',
                to='main.ExecutionEnvironment',
            ),
        ),
    ]
