# Generated by Django 2.2.16 on 2021-03-16 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0132_instancegroup_is_container_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='unifiedjob',
            name='ansible_version',
            field=models.CharField(blank=True, default='', editable=False, help_text='The version of Ansible Core installed in the execution environment.', max_length=50),
        ),
    ]
