# Generated by Django 2.2.16 on 2021-04-13 19:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('main', '0135_schedule_sort_fallback_to_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='scm_track_submodules',
            field=models.BooleanField(default=False, help_text='Track submodules latest commits on defined branch.'),
        ),
        migrations.AddField(
            model_name='projectupdate',
            name='scm_track_submodules',
            field=models.BooleanField(default=False, help_text='Track submodules latest commits on defined branch.'),
        ),
    ]
