# Generated by Django 2.2.16 on 2021-04-14 16:21

from django.db import migrations
from django.utils.timezone import now


def create_cleanup_ee_images(apps, schema_editor):
    SystemJobTemplate = apps.get_model('main', 'SystemJobTemplate')
    ContentType = apps.get_model('contenttypes', 'ContentType')
    sjt_ct = ContentType.objects.get_for_model(SystemJobTemplate)
    now_dt = now()
    sjt, created = SystemJobTemplate.objects.get_or_create(
        job_type='cleanup_images',
        defaults=dict(
            name='Cleanup Execution Environment Images',
            description='Remove unused execution environment images',
            created=now_dt,
            modified=now_dt,
            polymorphic_ctype=sjt_ct,
        ),
    )


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0135_schedule_sort_fallback_to_id'),
    ]

    operations = [
        migrations.RunPython(create_cleanup_ee_images),
    ]
