# Generated by Django 2.2.16 on 2021-02-02 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
<<<<<<< HEAD:awx/main/migrations/0136_scm_track_submodules.py
        ('main', '0135_schedule_sort_fallback_to_id'),
=======
        ('main', '0131_undo_org_polymorphic_ee'),
>>>>>>> Update and rename 0124_scm_track_submodules.py to 0132_scm_track_submodules.py:awx/main/migrations/0132_scm_track_submodules.py
    ]

    operations = [
        migrations.AddField(
            model_name='Project',
            name='scm_track_submodules',
            field=models.BooleanField(help_text='Track submodule latest commit on specified branch.'),
        ),
        migrations.AddField(
            model_name='ProjectUpdate',
            name='scm_track_submodules',
            field=models.BooleanField(help_text='Track submodule latest commit on specified branch.'),
        ),
        migrations.AlterField(
            model_name='project',
            name='scm_track_submodules',
            field=models.BooleanField(default=False, help_text='Track submodules latest commits on defined branch.'),
        ),
        migrations.AlterField(
            model_name='projectupdate',
            name='scm_track_submodules',
            field=models.BooleanField(default=False, help_text='Track submodules latest commits on defined branch.'),
        ),
    ]
