# Generated by Django 2.2.16 on 2021-04-13 19:51

from django.db import migrations

# AWX migration utils
from awx.main.migrations._inventory_source import delete_custom_inv_source


class Migration(migrations.Migration):
    dependencies = [
        ('main', '0136_scm_track_submodules'),
    ]

    operations = [
        migrations.RunPython(delete_custom_inv_source),
    ]
