# Generated by Django 2.2.16 on 2021-04-27 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0138_custom_inventory_scripts_removal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='webhook_service',
            field=models.CharField(
                blank=True,
                choices=[('github', 'GitHub'), ('gitlab', 'GitLab'), ('generic', 'Generic')],
                help_text='Service that webhook requests will be accepted from',
                max_length=16,
            ),
        ),
        migrations.AlterField(
            model_name='jobtemplate',
            name='webhook_service',
            field=models.CharField(
                blank=True,
                choices=[('github', 'GitHub'), ('gitlab', 'GitLab'), ('generic', 'Generic')],
                help_text='Service that webhook requests will be accepted from',
                max_length=16,
            ),
        ),
        migrations.AlterField(
            model_name='workflowjob',
            name='webhook_service',
            field=models.CharField(
                blank=True,
                choices=[('github', 'GitHub'), ('gitlab', 'GitLab'), ('generic', 'Generic')],
                help_text='Service that webhook requests will be accepted from',
                max_length=16,
            ),
        ),
        migrations.AlterField(
            model_name='workflowjobtemplate',
            name='webhook_service',
            field=models.CharField(
                blank=True,
                choices=[('github', 'GitHub'), ('gitlab', 'GitLab'), ('generic', 'Generic')],
                help_text='Service that webhook requests will be accepted from',
                max_length=16,
            ),
        ),
    ]
