# Generated by Django 2.2.16 on 2021-05-11 19:38

from django.db import migrations


def forwards(apps, schema_editor):
    Instance = apps.get_model('main', 'Instance')
    Instance.objects.filter(version__startswith='ansible-runner-').delete()


class Migration(migrations.Migration):
    dependencies = [
        ('main', '0140_rename'),
    ]

    operations = [
        migrations.RunPython(forwards),
    ]
