# Generated by Django 2.2.16 on 2021-05-18 18:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('main', '0142_update_ee_image_field_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='HostMetric',
            fields=[
                ('hostname', models.CharField(max_length=512, primary_key=True, serialize=False)),
                ('first_automation', models.DateTimeField(auto_now_add=True, db_index=True, help_text='When the host was first automated against')),
                ('last_automation', models.DateTimeField(db_index=True, help_text='When the host was last automated against')),
            ],
        ),
    ]
