# Generated by Django 2.2.16 on 2021-06-16 21:00

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('main', '0148_unifiedjob_receptor_unit_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventory',
            name='insights_credential',
        ),
    ]
