# Generated by Django 2.2.20 on 2021-07-27 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0151_rename_managed_by_tower'),
    ]

    operations = [
        migrations.AddField(
            model_name='credential',
            name='can_used_in_k8s',
            field=models.BooleanField(default=False),
        ),
    ]
