# Generated by Django 2.2.20 on 2021-12-17 19:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('main', '0155_improved_health_check'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instance',
            name='node_type',
            field=models.CharField(
                choices=[
                    ('control', 'Control plane node'),
                    ('execution', 'Execution plane node'),
                    ('hybrid', 'Controller and execution'),
                    ('hop', 'Message-passing node, no execution capability'),
                ],
                default='hybrid',
                max_length=16,
            ),
        ),
        migrations.CreateModel(
            name='InstanceLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='main.Instance')),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reverse_peers', to='main.Instance')),
            ],
            options={
                'unique_together': {('source', 'target')},
            },
        ),
        migrations.AddField(
            model_name='instance',
            name='peers',
            field=models.ManyToManyField(through='main.InstanceLink', to='main.Instance'),
        ),
    ]
