# Generated by Django 2.2.20 on 2022-01-18 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0156_capture_mesh_topology'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory',
            name='labels',
            field=models.ManyToManyField(blank=True, help_text='Labels associated with this inventory.', related_name='inventory_labels', to='main.Label'),
        ),
    ]
