# Generated by Django 2.2.24 on 2022-02-14 17:37

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('main', '0157_inventory_labels'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instance',
            name='cpu',
            field=models.DecimalField(decimal_places=1, default=Decimal('0'), editable=False, max_digits=4),
        ),
    ]
