# Generated by Django 3.2.12 on 2022-03-31 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0158_make_instance_cpu_decimal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventorysource',
            name='update_on_project_update',
            field=models.BooleanField(
                default=False,
                help_text='This field is deprecated and will be removed in a future release. In future release, functionality will be migrated to source project update_on_launch.',
            ),
        ),
    ]
