# Generated by Django 3.2.12 on 2022-04-20 04:54

import awx.main.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0158_make_instance_cpu_decimal'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='integrity_result',
            field=awx.main.fields.JSONBlob(blank=True, default=None, editable=False, help_text='Overall result of integrity verification', null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='integrity_verified',
            field=models.BooleanField(blank=True, default=None, editable=False, help_text='Whether integrity verification passed or not', null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='playbook_integrity_enabled',
            field=models.BooleanField(blank=True, default=None, help_text='Enable integrity check for playbook and override the global flag', null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='playbook_integrity_latest_result',
            field=awx.main.fields.JSONBlob(blank=True, default=None, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='playbook_integrity_public_key',
            field=models.TextField(blank=True, default='', help_text='A base64 encoded public key for playbook verification'),
        ),
        migrations.AddField(
            model_name='project',
            name='playbook_integrity_signature_type',
            field=models.CharField(
                blank=True,
                choices=[('gpg', 'GPG'), ('sigstore', 'Sigstore')],
                default='gpg',
                help_text='A signature type for playbook integrity check',
                max_length=128,
                verbose_name='signature type for playbook integrity check',
            ),
        ),
        migrations.AddField(
            model_name='projectupdate',
            name='playbook_integrity_result',
            field=awx.main.fields.JSONBlob(blank=True, default=None, editable=False, null=True),
        ),
    ]