# Generated by Django 3.2.12 on 2022-05-11 20:41

import awx.main.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0161_unifiedjob_host_status_counts'),
    ]

    operations = [
        migrations.AddField(
            model_name='workflowjob',
            name='artifacts',
            field=awx.main.fields.JSONBlob(blank=True, default=dict, editable=False),
        ),
    ]
