# Generated by Django 3.2.13 on 2022-05-02 21:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('main', '0161_unifiedjob_host_status_counts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unifiedjob',
            name='dependent_jobs',
            field=models.ManyToManyField(editable=False, related_name='unifiedjob_blocked_jobs', to='main.UnifiedJob'),
        ),
    ]
