# Generated by Django 3.2.13 on 2022-06-02 18:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('main', '0162_alter_unifiedjob_dependent_jobs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='job_tags',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='jobtemplate',
            name='job_tags',
            field=models.TextField(blank=True, default=''),
        ),
    ]
