# Generated by Django 3.2.13 on 2022-05-17 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0162_alter_unifiedjob_dependent_jobs'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='fqcn_role',
            field=models.CharField(
                blank=True,
                default='',
                help_text='Fully Qualified Name Referencing a Role.This needs to be preloaded and available in the Execution Environment',
                max_length=1024,
            ),
        ),
        migrations.AddField(
            model_name='jobtemplate',
            name='fqcn_role',
            field=models.CharField(
                blank=True,
                default='',
                help_text='Fully Qualified Name Referencing a Role.This needs to be preloaded and available in the Execution Environment',
                max_length=1024,
            ),
        ),
    ]
