# Generated by Django 3.2.13 on 2022-07-19 13:54

from django.db import migrations, models


def forwards(apps, schema_editor):
    # All existing InstanceLink objects need to be in the state
    # 'Established', which is the default, so nothing needs to be done
    # for that.

    Instance = apps.get_model('main', 'Instance')
    for instance in Instance.objects.all():
        instance.node_state = 'ready' if not instance.errors else 'unavailable'
        instance.save(update_fields=['node_state'])


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0164_remove_inventorysource_update_on_project_update'),
    ]

    operations = [
        migrations.AddField(
            model_name='instance',
            name='node_state',
            field=models.CharField(
                choices=[
                    ('provisioning', 'Provisioning'),
                    ('provision-fail', 'Provisioning Failure'),
                    ('installed', 'Installed'),
                    ('ready', 'Ready'),
                    ('unavailable', 'Unavailable'),
                    ('deprovisioning', 'De-provisioning'),
                    ('deprovision-fail', 'De-provisioning Failure'),
                ],
                default='ready',
                max_length=16,
            ),
        ),
        migrations.AddField(
            model_name='instancelink',
            name='link_state',
            field=models.CharField(
                choices=[('adding', 'Adding'), ('established', 'Established'), ('removing', 'Removing')], default='established', max_length=16
            ),
        ),
        migrations.RunPython(forwards, reverse_code=migrations.RunPython.noop),
    ]
