# Generated by Django 3.2.13 on 2022-07-12 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0164_remove_inventorysource_update_on_project_update'),
    ]

    operations = [
        migrations.AddField(
            model_name='workflowapproval',
            name='expires',
            field=models.DateTimeField(
                default=None,
                editable=False,
                help_text='The time this approval will expire. This is the created time plus timeout, used for filtering.',
                null=True,
            ),
        ),
    ]
