# Generated by Django 3.2.13 on 2022-06-30 19:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0164_remove_inventorysource_update_on_project_update'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adhoccommandevent',
            name='host',
            field=models.ForeignKey(
                default=None, editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='ad_hoc_command_events', to='main.host'
            ),
        ),
        migrations.AlterField(
            model_name='jobevent',
            name='host',
            field=models.IntegerField(default=None, editable=False, null=True),
        ),
    ]
