# Generated by Django 3.2.13 on 2022-07-06 13:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0165_task_manager_refactor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adhoccommandevent',
            name='host',
            field=models.ForeignKey(
                db_constraint=False,
                default=None,
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='ad_hoc_command_events',
                to='main.host',
            ),
        ),
        migrations.AlterField(
            model_name='jobevent',
            name='host',
            field=models.ForeignKey(
                db_constraint=False,
                default=None,
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name='job_events_as_primary_host',
                to='main.host',
            ),
        ),
    ]
