# Generated by Django 3.2.13 on 2022-08-18 15:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0166_task_manager_refactor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='signature_validation',
        ),
    ]
