# Generated by Django 3.2.13 on 2022-07-20 17:46

from django.db import migrations, models
import django.db.models.deletion

from awx.main.models import CredentialType
from awx.main.utils.common import set_current_apps


def setup_tower_managed_defaults(apps, schema_editor):
    set_current_apps(apps)
    CredentialType.setup_tower_managed_defaults(apps)


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0166_alter_jobevent_host'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='signature_validation',
            field=models.BooleanField(default=False, help_text='Enable signature validation.'),
        ),
        migrations.AddField(
            model_name='project',
            name='signature_validation_credential',
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='projects_signature_validation',
                to='main.credential',
            ),
        ),
        migrations.RunPython(setup_tower_managed_defaults),
        migrations.RemoveField(
            model_name='project',
            name='signature_validation',
        ),
        migrations.AlterField(
            model_name='project',
            name='signature_validation_credential',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.credential'),
        ),
    ]
