# Generated by Django 3.2.13 on 2022-09-08 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0167_project_signature_validation_credential'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventoryupdate',
            name='scm_revision',
            field=models.CharField(
                blank=True,
                default='',
                editable=False,
                help_text='The SCM Revision from the Project used for this inventory update.  Only applicable to inventories source from scm',
                max_length=1024,
                verbose_name='SCM Revision',
            ),
        ),
    ]
