# Generated by Django 3.2.13 on 2022-09-09 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0167_project_signature_validation_credential'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory',
            name='prevent_instance_group_fallback',
            field=models.BooleanField(
                default=False,
                help_text='If enabled, the inventory will prevent adding any organization instance groups to the list of preferred instances groups to run associated job templates on.',
            ),
        ),
        migrations.AddField(
            model_name='jobtemplate',
            name='prevent_instance_group_fallback',
            field=models.BooleanField(
                default=False,
                help_text='If enabled, the job template will prevent adding any inventory or organization instance groups to the list of preferred instances groups to run on.',
            ),
        ),
    ]
