# Generated by Django 3.2.13 on 2022-08-18 18:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0167_remove_project_signature_validation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='signature_validation_credential',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.credential'),
        ),
    ]
