# Generated by Django 3.2.13 on 2022-09-26 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0170_node_and_link_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory',
            name='prevent_instance_group_fallback',
            field=models.BooleanField(
                default=False,
                help_text='If enabled, the inventory will prevent adding any organization instance groups to the list of preferred instances groups to run associated job templates on.If this setting is enabled and you provided an empty list, the global instance groups will be applied.',
            ),
        ),
        migrations.AddField(
            model_name='jobtemplate',
            name='prevent_instance_group_fallback',
            field=models.BooleanField(
                default=False,
                help_text='If enabled, the job template will prevent adding any inventory or organization instance groups to the list of preferred instances groups to run on.If this setting is enabled and you provided an empty list, the global instance groups will be applied.',
            ),
        ),
    ]
