# Generated by Django 3.2.13 on 2022-09-29 13:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0171_add_health_check_started'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='survey_passwords',
        ),
        migrations.RemoveField(
            model_name='workflowjob',
            name='survey_passwords',
        ),
        migrations.RemoveField(
            model_name='joblaunchconfig',
            name='survey_passwords',
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='survey_passwords',
        ),
        migrations.RemoveField(
            model_name='workflowjobnode',
            name='survey_passwords',
        ),
        migrations.RemoveField(
            model_name='workflowjobtemplatenode',
            name='survey_passwords',
        ),
    ]
