# Generated by Django 3.2.13 on 2022-11-18 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0172_prevent_instance_fallback'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory',
            name='source_inventories',
            field=models.ManyToManyField(
                blank=True,
                help_text='Only valid for multiple inventories, this links to the inventories that will be used.',
                related_name='destination_inventories',
                to='main.Inventory',
            ),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='kind',
            field=models.CharField(
                blank=True,
                choices=[
                    ('', 'Hosts have a direct link to this inventory.'),
                    ('smart', 'Hosts for inventory generated using the host_filter property.'),
                    ('multiple', 'Contains links to several other inventories to run automation against them all at the same time.'),
                ],
                default='',
                help_text='Kind of inventory being represented.',
                max_length=32,
            ),
        ),
    ]
