# Generated by Django 3.2.16 on 2022-12-07 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0173_instancegroup_max_limits'),
    ]

    operations = [
        migrations.AddField(
            model_name='workflowjob',
            name='is_bulk_job',
            field=models.BooleanField(default=False),
        ),
    ]
