# Generated by Django 3.2.13 on 2022-12-13 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0173_instancegroup_max_limits'),
    ]

    operations = [
        migrations.AlterField(
            model_name='executionenvironment',
            name='pull',
            field=models.CharField(blank=True, choices=[('always', 'Always pull container before running.'), ('missing', 'Only pull the image if not present before running.'), ('never', 'Never pull container before running.'), ('newer', 'Only pull if a newer image is available in the registry.')], default='', help_text='Pull image before running?', max_length=16),
        ),
    ]