# Generated by Django 3.2.16 on 2022-12-07 21:11

from django.db import migrations

from awx.main.migrations import _rbac as rbac
from awx.main.migrations import _migration_utils as migration_utils


class Migration(migrations.Migration):
    dependencies = [
        ('main', '0173_instancegroup_max_limits'),
    ]

    operations = [
        migrations.RunPython(migration_utils.set_current_apps_for_migrations),
        migrations.RunPython(rbac.create_roles),
    ]
