# Generated by Django 3.2.16 on 2023-03-03 20:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('main', '0174_ensure_org_ee_admin_roles'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventorysource',
            name='scm_branch',
            field=models.CharField(
                blank=True,
                default='',
                help_text='Inventory source SCM branch. Project default used if blank. Only allowed if project allow_override field is set to true.',
                max_length=1024,
            ),
        ),
        migrations.AddField(
            model_name='inventoryupdate',
            name='scm_branch',
            field=models.CharField(
                blank=True,
                default='',
                help_text='Inventory source SCM branch. Project default used if blank. Only allowed if project allow_override field is set to true.',
                max_length=1024,
            ),
        ),
    ]
