# Generated by Django 2.2.20 on 2021-08-04 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0174_ensure_org_ee_admin_roles'),
    ]

    operations = [
        migrations.AddField(
            model_name='workflowapproval',
            name='approve_self',
            field=models.BooleanField(default=True, help_text='Allow user to approve their own tasks'),
        ),
        migrations.AddField(
            model_name='workflowapprovaltemplate',
            name='approve_self',
            field=models.BooleanField(default=True, help_text='Allow user to approve their own tasks'),
        ),
    ]
