# Generated by Django 3.2.16 on 2023-01-05 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0174_ensure_org_ee_admin_roles'),
    ]

    operations = [
        migrations.AddField(
            model_name='workflowjob',
            name='is_bulk_job',
            field=models.BooleanField(default=False),
        ),
    ]
