# Generated by Django 3.2.16 on 2023-02-10 12:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('main', '0175_add_hostmetric_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='HostMetricSummaryMonthly',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('license_consumed', models.BigIntegerField(default=0, help_text='How much unique hosts are consumed from the license')),
                ('license_capacity', models.BigIntegerField(default=0, help_text="'License capacity as max. number of unique hosts")),
                (
                    'hosts_added',
                    models.IntegerField(default=0, help_text='How many hosts were added in the associated month, consuming more license capacity'),
                ),
                (
                    'hosts_deleted',
                    models.IntegerField(default=0, help_text='How many hosts were deleted in the associated month, freeing the license capacity'),
                ),
                (
                    'indirectly_managed_hosts',
                    models.IntegerField(default=0, help_text='Manually entered number indirectly managed hosts for a certain month'),
                ),
            ],
        ),
    ]
