# Generated by Django 3.2.16 on 2023-02-17 02:45

from django.db import migrations
from awx.main.migrations import _rbac as rbac
from awx.main.migrations import _migration_utils as migration_utils
from awx.main.migrations import _OrgAdmin_to_use_ig as oamigrate
from awx.main.migrations import ActivityStreamDisabledMigration


class Migration(ActivityStreamDisabledMigration):
    dependencies = [
        ('main', '0177_instance_group_role_addition'),
    ]
    operations = [
        migrations.RunPython(migration_utils.set_current_apps_for_migrations),
        migrations.RunPython(rbac.create_roles),
        migrations.RunPython(oamigrate.migrate_org_admin_to_use),
    ]
