# Generated by Django 3.2.16 on 2023-04-21 14:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('main', '0182_constructed_inventory'),
    ]

    operations = [
        migrations.AddField(
            model_name='oauth2application',
            name='algorithm',
            field=models.CharField(
                blank=True, choices=[('', 'No OIDC support'), ('RS256', 'RSA with SHA-2 256'), ('HS256', 'HMAC with SHA-2 256')], default='', max_length=5
            ),
        ),
    ]
