# Generated by Django 3.2.16 on 2023-05-03 20:05

from django.db import migrations
import sortedm2m.fields


class Migration(migrations.Migration):
    dependencies = [
        ('main', '0182_constructed_inventory'),
    ]

    operations = [
        # handle galaxy_credentials field
        migrations.AlterModelTable(
            name='organizationgalaxycredentialmembership',
            table='main_organization_galaxy_credentials',
        ),
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.RemoveField(
                    model_name='organization',
                    name='galaxy_credentials',
                ),
                migrations.DeleteModel(
                    name='OrganizationGalaxyCredentialMembership',
                ),
                migrations.AddField(
                    model_name='organization',
                    name='galaxy_credentials',
                    field=sortedm2m.fields.SortedManyToManyField(
                        blank=True, help_text=None, related_name='orgs_using_as_galaxy', sort_value_field_name='position', to='main.Credential'
                    ),
                ),
            ]
        ),
        # handle input_inventories field, more complex due to symmetrical thing
        migrations.RenameField(
            model_name='inventoryconstructedinventorymembership',
            old_name='constructed_inventory',
            new_name='from_inventory',
        ),
        migrations.RenameField(
            model_name='inventoryconstructedinventorymembership',
            old_name='input_inventory',
            new_name='to_inventory',
        ),
        migrations.AlterModelTable(
            name='inventoryconstructedinventorymembership',
            table='main_inventory_input_inventories',
        ),
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.RemoveField(
                    model_name='inventory',
                    name='input_inventories',
                ),
                migrations.DeleteModel(
                    name='InventoryConstructedInventoryMembership',
                ),
                migrations.AddField(
                    model_name='inventory',
                    name='input_inventories',
                    field=sortedm2m.fields.SortedManyToManyField(
                        blank=True,
                        help_text='Only valid for constructed inventories, this links to the inventories that will be used.',
                        related_name='destination_inventories',
                        sort_value_field_name='position',
                        to='main.Inventory',
                    ),
                ),
            ]
        ),
        # handle instance_groups relationships, the through table names already align for this
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.RemoveField(
                    model_name='inventory',
                    name='instance_groups',
                ),
                migrations.RemoveField(
                    model_name='joblaunchconfig',
                    name='instance_groups',
                ),
                migrations.RemoveField(
                    model_name='organization',
                    name='instance_groups',
                ),
                migrations.RemoveField(
                    model_name='schedule',
                    name='instance_groups',
                ),
                migrations.RemoveField(
                    model_name='unifiedjobtemplate',
                    name='instance_groups',
                ),
                migrations.RemoveField(
                    model_name='workflowjob',
                    name='instance_groups',
                ),
                migrations.RemoveField(
                    model_name='workflowjobnode',
                    name='instance_groups',
                ),
                migrations.RemoveField(
                    model_name='workflowjobtemplatenode',
                    name='instance_groups',
                ),
                migrations.DeleteModel(
                    name='InventoryInstanceGroupMembership',
                ),
                migrations.DeleteModel(
                    name='JobLaunchConfigInstanceGroupMembership',
                ),
                migrations.DeleteModel(
                    name='OrganizationInstanceGroupMembership',
                ),
                migrations.DeleteModel(
                    name='ScheduleInstanceGroupMembership',
                ),
                migrations.DeleteModel(
                    name='UnifiedJobTemplateInstanceGroupMembership',
                ),
                migrations.DeleteModel(
                    name='WorkflowJobInstanceGroupMembership',
                ),
                migrations.DeleteModel(
                    name='WorkflowJobNodeBaseInstanceGroupMembership',
                ),
                migrations.DeleteModel(
                    name='WorkflowJobTemplateNodeBaseInstanceGroupMembership',
                ),
                migrations.AddField(
                    model_name='inventory',
                    name='instance_groups',
                    field=sortedm2m.fields.SortedManyToManyField(blank=True, help_text=None, related_name='inventory_instance_groups', to='main.InstanceGroup'),
                ),
                migrations.AddField(
                    model_name='joblaunchconfig',
                    name='instance_groups',
                    field=sortedm2m.fields.SortedManyToManyField(
                        editable=False, help_text=None, related_name='launch_config_instance_groups', to='main.InstanceGroup'
                    ),
                ),
                migrations.AddField(
                    model_name='organization',
                    name='instance_groups',
                    field=sortedm2m.fields.SortedManyToManyField(
                        blank=True, help_text=None, related_name='organization_instance_groups', to='main.InstanceGroup'
                    ),
                ),
                migrations.AddField(
                    model_name='schedule',
                    name='instance_groups',
                    field=sortedm2m.fields.SortedManyToManyField(
                        blank=True, editable=False, help_text=None, related_name='schedule_instance_groups', to='main.InstanceGroup'
                    ),
                ),
                migrations.AddField(
                    model_name='unifiedjobtemplate',
                    name='instance_groups',
                    field=sortedm2m.fields.SortedManyToManyField(
                        blank=True, help_text=None, related_name='unifiedjobtemplate_instance_groups', to='main.InstanceGroup'
                    ),
                ),
                migrations.AddField(
                    model_name='workflowjob',
                    name='instance_groups',
                    field=sortedm2m.fields.SortedManyToManyField(
                        blank=True, editable=False, help_text=None, related_name='workflow_job_instance_groups', to='main.InstanceGroup'
                    ),
                ),
                migrations.AddField(
                    model_name='workflowjobnode',
                    name='instance_groups',
                    field=sortedm2m.fields.SortedManyToManyField(
                        blank=True, editable=False, help_text=None, related_name='workflow_job_node_instance_groups', to='main.InstanceGroup'
                    ),
                ),
                migrations.AddField(
                    model_name='workflowjobtemplatenode',
                    name='instance_groups',
                    field=sortedm2m.fields.SortedManyToManyField(
                        blank=True, editable=False, help_text=None, related_name='workflow_job_template_node_instance_groups', to='main.InstanceGroup'
                    ),
                ),
            ]
        ),
    ]
