# Generated by Django 3.2.16 on 2023-05-03 20:05

from django.db import migrations
import sortedm2m.fields


class Migration(migrations.Migration):
    dependencies = [
        ('main', '0182_constructed_inventory'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='organizationgalaxycredentialmembership',
            table='main_organization_galaxy_credentials',
        ),
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.RemoveField(
                    model_name='organization',
                    name='galaxy_credentials',
                ),
                migrations.AddField(
                    model_name='organization',
                    name='galaxy_credentials',
                    field=sortedm2m.fields.SortedManyToManyField(blank=True, help_text=None, related_name='orgs_using_as_galaxy', to='main.Credential'),
                ),
                migrations.DeleteModel(
                    name='OrganizationGalaxyCredentialMembership',
                ),
            ]
        ),
    ]
