# Generated by Django 3.2.16 on 2023-04-20 19:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('main', '0182_constructed_inventory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instancelink',
            name='link_state',
            field=models.CharField(
                choices=[('adding', 'Adding'), ('established', 'Established'), ('removing', 'Removing')],
                default='adding',
                help_text='Indicates the current life cycle stage of this peer link.',
                max_length=16,
            ),
        ),
    ]
