# Generated by Django 3.2.16 on 2023-04-21 14:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.OAUTH2_PROVIDER_ID_TOKEN_MODEL),
        ('main', '0182_constructed_inventory'),
        ('oauth2_provider', '0005_auto_20211222_2352'),
    ]

    operations = [
        migrations.AddField(
            model_name='oauth2accesstoken',
            name='id_token',
            field=models.OneToOneField(
                blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='access_token', to=settings.OAUTH2_PROVIDER_ID_TOKEN_MODEL
            ),
        ),
        migrations.AddField(
            model_name='oauth2application',
            name='algorithm',
            field=models.CharField(
                blank=True, choices=[('', 'No OIDC support'), ('RS256', 'RSA with SHA-2 256'), ('HS256', 'HMAC with SHA-2 256')], default='', max_length=5
            ),
        ),
    ]
