# Generated by Django 3.2.16 on 2023-04-24 20:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('main', '0183_alter_instancelink_link_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='instance',
            name='peer_to_control_nodes',
            field=models.BooleanField(default=False, help_text='If True, control plane cluster nodes should automatically peer to it.'),
        ),
    ]
