# Generated by Django 4.2 on 2023-05-26 14:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('main', '0184_django_indexes'),
    ]

    operations = [
        migrations.AddField(
            model_name='unifiedjobtemplate',
            name='job_name_template',
            field=models.TextField(blank=True, help_text='Jinja template for the name of the job launched from the template.', null=True),
        ),
    ]
