# Generated by Django 4.2 on 2023-06-09 19:51

import awx.main.models.notifications
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('main', '0184_django_indexes'),
        ('conf', '0010_change_to_JSONField'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activitystream',
            name='deleted_actor',
            field=models.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name='activitystream',
            name='setting',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='instancegroup',
            name='policy_instance_list',
            field=models.JSONField(
                blank=True, default=list, help_text='List of exact-match Instances that will always be automatically assigned to this group'
            ),
        ),
        migrations.AlterField(
            model_name='job',
            name='survey_passwords',
            field=models.JSONField(blank=True, default=dict, editable=False),
        ),
        migrations.AlterField(
            model_name='joblaunchconfig',
            name='char_prompts',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='joblaunchconfig',
            name='survey_passwords',
            field=models.JSONField(blank=True, default=dict, editable=False),
        ),
        migrations.AlterField(
            model_name='jobtemplate',
            name='survey_spec',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='notification',
            name='body',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='notificationtemplate',
            name='messages',
            field=models.JSONField(
                blank=True,
                default=awx.main.models.notifications.NotificationTemplate.default_messages,
                help_text='Optional custom messages for notification template.',
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name='notificationtemplate',
            name='notification_configuration',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='project',
            name='inventory_files',
            field=models.JSONField(
                blank=True,
                default=list,
                editable=False,
                help_text='Suggested list of content that could be Ansible inventory in the project',
                verbose_name='Inventory Files',
            ),
        ),
        migrations.AlterField(
            model_name='project',
            name='playbook_files',
            field=models.JSONField(blank=True, default=list, editable=False, help_text='List of playbooks found in the project', verbose_name='Playbook Files'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='char_prompts',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='survey_passwords',
            field=models.JSONField(blank=True, default=dict, editable=False),
        ),
        migrations.AlterField(
            model_name='unifiedjob',
            name='job_env',
            field=models.JSONField(blank=True, default=dict, editable=False),
        ),
        migrations.AlterField(
            model_name='workflowjob',
            name='char_prompts',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='workflowjob',
            name='survey_passwords',
            field=models.JSONField(blank=True, default=dict, editable=False),
        ),
        migrations.AlterField(
            model_name='workflowjobnode',
            name='char_prompts',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='workflowjobnode',
            name='survey_passwords',
            field=models.JSONField(blank=True, default=dict, editable=False),
        ),
        migrations.AlterField(
            model_name='workflowjobtemplate',
            name='char_prompts',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='workflowjobtemplate',
            name='survey_spec',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='workflowjobtemplatenode',
            name='char_prompts',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='workflowjobtemplatenode',
            name='survey_passwords',
            field=models.JSONField(blank=True, default=dict, editable=False),
        ),
    ]
