# Generated by Django 3.2.16 on 2022-12-14 20:05

from django.db import migrations, models

from awx.main.migrations._create_system_jobs import create_system_job_templates


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0185_move_JSONBlob_to_JSONField'),
    ]

    operations = [
        migrations.AlterField(
            model_name='systemjob',
            name='job_type',
            field=models.CharField(
                blank=True,
                choices=[
                    ('cleanup_jobs', 'Remove jobs older than a certain number of days'),
                    ('cleanup_activitystream', 'Remove activity stream entries older than a certain number of days'),
                    ('cleanup_sessions', 'Removes expired browser sessions from the database'),
                    ('cleanup_tokens', 'Removes expired OAuth 2 access tokens and refresh tokens'),
                    ('run_health_checks', 'Runs health checks for instances with node types that can run jobs'),
                ],
                default='',
                max_length=32,
            ),
        ),
        migrations.AlterField(
            model_name='systemjobtemplate',
            name='job_type',
            field=models.CharField(
                blank=True,
                choices=[
                    ('cleanup_jobs', 'Remove jobs older than a certain number of days'),
                    ('cleanup_activitystream', 'Remove activity stream entries older than a certain number of days'),
                    ('cleanup_sessions', 'Removes expired browser sessions from the database'),
                    ('cleanup_tokens', 'Removes expired OAuth 2 access tokens and refresh tokens'),
                    ('run_health_checks', 'Runs health checks for instances with node types that can run jobs'),
                ],
                default='',
                max_length=32,
            ),
        ),
        migrations.RunPython(create_system_job_templates, migrations.RunPython.noop),
    ]
