# Generated by Django 4.2 on 2023-06-30 12:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('main', '0185_move_JSONBlob_to_JSONField'),
    ]

    operations = [
        migrations.AlterField(
            model_name='credentialtype',
            name='kind',
            field=models.CharField(
                choices=[
                    ('ssh', 'Machine'),
                    ('vault', 'Vault'),
                    ('net', 'Network'),
                    ('scm', 'Source Control'),
                    ('cloud', 'Cloud'),
                    ('registry', 'Container Registry'),
                    ('token', 'Personal Access Token'),
                    ('insights', 'Insights'),
                    ('external', 'External'),
                    ('kubernetes', 'Kubernetes'),
                    ('galaxy', 'Galaxy/Automation Hub'),
                    ('cryptography', 'Cryptography'),
                    ('sigstore', 'Sigstore'),
                ],
                max_length=32,
            ),
        ),
    ]
