# Generated by Django 4.2.5 on 2023-10-04 06:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('main', '0187_hop_nodes'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReceptorAddress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=255)),
                ('port', models.IntegerField(null=True)),
                ('protocol', models.CharField(max_length=10)),
                ('websocket_path', models.CharField(blank=True, default='', max_length=255)),
                ('is_internal', models.BooleanField(default=False)),
                ('instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receptor_addresses', to='main.instance')),
            ],
        ),
        migrations.AddConstraint(
            model_name='receptoraddress',
            constraint=models.UniqueConstraint(
                condition=models.Q(('port', None)),
                fields=('address', 'protocol', 'websocket_path'),
                name='unique_receptor_address_no_port',
                violation_error_message='Receptor address must be unique.',
            ),
        ),
        migrations.AddConstraint(
            model_name='receptoraddress',
            constraint=models.UniqueConstraint(
                condition=models.Q(('port', None), _negated=True),
                fields=('address', 'port', 'protocol', 'websocket_path'),
                name='unique_receptor_address_with_port',
                violation_error_message='Receptor address must be unique.',
            ),
        ),
    ]
