# Generated by Django 4.2.3 on 2023-08-31 12:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('main', '0187_hop_nodes'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='scm_depth',
            field=models.IntegerField(blank=True, null=True, help_text='Specifies the depth to checkout.', verbose_name='SCM depth'),
        ),
        migrations.AddField(
            model_name='projectupdate',
            name='scm_depth',
            field=models.IntegerField(blank=True, null=True, help_text='Specifies the depth to checkout.', verbose_name='SCM depth'),
        ),
    ]
