# Generated by Django 4.2.6 on 2023-11-15 17:32

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('main', '0187_hop_nodes'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReceptorAddress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(help_text='Routable address for this instance.', max_length=255)),
                (
                    'port',
                    models.IntegerField(
                        default=27199,
                        help_text='Port for the address.',
                        validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(65535)],
                    ),
                ),
                (
                    'protocol',
                    models.CharField(
                        choices=[('tcp', 'TCP'), ('ws', 'WS'), ('wss', 'WSS')],
                        default='tcp',
                        help_text="Protocol to use when connecting, 'tcp', 'wss', or 'ws'.",
                        max_length=10,
                    ),
                ),
                ('websocket_path', models.CharField(blank=True, default='', help_text='Websocket path.', max_length=255)),
                ('is_internal', models.BooleanField(default=False, help_text='If True, only routable inside of the Kubernetes cluster.')),
                (
                    'peers_from_control_nodes',
                    models.BooleanField(default=False, help_text='If True, control plane cluster nodes should automatically peer to it.'),
                ),
            ],
        ),
        migrations.RemoveConstraint(
            model_name='instancelink',
            name='source_and_target_can_not_be_equal',
        ),
        migrations.AlterUniqueTogether(
            name='instancelink',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='instance',
            name='listener_port',
        ),
        migrations.AlterField(
            model_name='instancelink',
            name='source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.instance'),
        ),
        migrations.AddConstraint(
            model_name='instancelink',
            constraint=models.UniqueConstraint(fields=('source', 'target'), name='source_target_unique_together'),
        ),
        migrations.AddField(
            model_name='receptoraddress',
            name='instance',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receptor_addresses', to='main.instance'),
        ),
        migrations.AddField(
            model_name='activitystream',
            name='receptor_address',
            field=models.ManyToManyField(blank=True, to='main.receptoraddress'),
        ),
        migrations.AlterField(
            model_name='instance',
            name='peers',
            field=models.ManyToManyField(related_name='peers_from', through='main.InstanceLink', to='main.receptoraddress'),
        ),
        migrations.AlterField(
            model_name='instancelink',
            name='target',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.receptoraddress'),
        ),
        migrations.AddConstraint(
            model_name='receptoraddress',
            constraint=models.UniqueConstraint(
                fields=('address', 'protocol'), name='unique_receptor_address', violation_error_message='Receptor address + protocol must be unique.'
            ),
        ),
    ]
