# Generated by Django 3.2.16 on 2023-02-10 19:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('main', '0189_inbound_hop_nodes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unifiedjobtemplate',
            name='status',
            field=models.CharField(
                choices=[
                    ('new', 'New'),
                    ('pending', 'Pending'),
                    ('waiting', 'Waiting'),
                    ('running', 'Running'),
                    ('successful', 'Successful'),
                    ('failed', 'Failed'),
                    ('error', 'Error'),
                    ('canceled', 'Canceled'),
                    ('never updated', 'Never Updated'),
                    ('ok', 'OK'),
                    ('missing', 'Missing'),
                    ('none', 'No External Source'),
                    ('updating', 'Updating'),
                ],
                default='never updated',
                editable=False,
                max_length=32,
            ),
        ),
    ]
