# Generated by Django 4.2.6 on 2023-11-20 16:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('main', '0190_add_django_permissions'),
    ]
    run_before = [
        ('dab_rbac', '__first__'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='is_system_auditor',
            field=models.BooleanField(default=False, help_text='Can view everying in the system, proxies to User model'),
        ),
    ]
