# Generated by Django 4.2.6 on 2023-11-21 02:06

from django.db import migrations

from awx.main.migrations._dab_rbac import migrate_to_new_rbac, create_permissions_as_operation, setup_managed_role_definitions


class Migration(migrations.Migration):
    dependencies = [
        ('main', '0191_add_django_permissions'),
        ('dab_rbac', '__first__'),
    ]

    operations = [
        # make sure permissions and content types have been created by now
        # these normally run in a post_migrate signal but we need them for our logic
        migrations.RunPython(create_permissions_as_operation, migrations.RunPython.noop),
        migrations.RunPython(setup_managed_role_definitions, migrations.RunPython.noop),
        migrations.RunPython(migrate_to_new_rbac, migrations.RunPython.noop),
    ]
