# Generated by Django 4.2.6 on 2024-05-08 07:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('main', '0192_custom_roles'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(
                choices=[
                    ('awssns', 'AWS SNS'),
                    ('email', 'Email'),
                    ('grafana', 'Grafana'),
                    ('irc', 'IRC'),
                    ('mattermost', 'Mattermost'),
                    ('pagerduty', 'Pagerduty'),
                    ('rocketchat', 'Rocket.Chat'),
                    ('slack', 'Slack'),
                    ('twilio', 'Twilio'),
                    ('webhook', 'Webhook'),
                ],
                max_length=32,
            ),
        ),
        migrations.AlterField(
            model_name='notificationtemplate',
            name='notification_type',
            field=models.CharField(
                choices=[
                    ('awssns', 'AWS SNS'),
                    ('email', 'Email'),
                    ('grafana', 'Grafana'),
                    ('irc', 'IRC'),
                    ('mattermost', 'Mattermost'),
                    ('pagerduty', 'Pagerduty'),
                    ('rocketchat', 'Rocket.Chat'),
                    ('slack', 'Slack'),
                    ('twilio', 'Twilio'),
                    ('webhook', 'Webhook'),
                ],
                max_length=32,
            ),
        ),
    ]
