# Generated by Django 4.2.6 on 2024-06-20 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0194_alter_inventorysource_source_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='executionenvironment',
            options={'default_permissions': ('add', 'change', 'delete'), 'ordering': ('-created',)},
        ),
    ]
