# Generated by Django 4.2.6 on 2024-06-20 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0194_alter_inventorysource_source_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='oauth2application',
            name='post_logout_redirect_uris',
            field=models.TextField(blank=True, help_text='Allowed Post Logout URIs list, space separated'),
        ),
    ]
