# Generated by Django 4.2.10 on 2024-08-09 16:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0195_EE_permissions'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
