# Generated by Django 4.2.10 on 2024-08-07 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0195_EE_permissions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activitystream',
            name='o_auth2_access_token',
        ),
        migrations.RemoveField(
            model_name='activitystream',
            name='o_auth2_application',
        ),
        migrations.AlterField(
            model_name='oauth2application',
            name='client_id',
            field=models.CharField(db_index=True, default=lambda: "", max_length=100, unique=True),
        ),
        migrations.DeleteModel(
            name='OAuth2AccessToken',
        ),
    ]
