# Generated by Django 4.2.18 on 2025-03-17 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0196_indirect_managed_node_audit'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory',
            name='opa_query_path',
            field=models.CharField(
                blank=True,
                default=None,
                help_text='The query path for the OPA policy to evaluate prior to job execution. The query path should be formatted as package/rule.',
                max_length=128,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name='jobtemplate',
            name='opa_query_path',
            field=models.CharField(
                blank=True,
                default=None,
                help_text='The query path for the OPA policy to evaluate prior to job execution. The query path should be formatted as package/rule.',
                max_length=128,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name='organization',
            name='opa_query_path',
            field=models.CharField(
                blank=True,
                default=None,
                help_text='The query path for the OPA policy to evaluate prior to job execution. The query path should be formatted as package/rule.',
                max_length=128,
                null=True,
            ),
        ),
    ]
