# Generated by Django 4.2.10 on 2024-09-16 10:22

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('main', '0196_indirect_managed_node_audit'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
