# Generated by Django 4.2.10 on 2024-10-16 17:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0196_alter_inventorysource_source_and_more'),
        ('main', '0197_remove_sso_app_content'),
    ]

    operations = []
