# Generated by Django 4.2.10 on 2024-09-16 10:22

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('main', '0198_alter_inventorysource_source_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
