# Generated by Django 4.2.10 on 2024-10-24 14:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0199_alter_inventorysource_source_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='oauth2application',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='oauth2application',
            name='organization',
        ),
        migrations.RemoveField(
            model_name='oauth2application',
            name='user',
        ),
        migrations.RemoveField(
            model_name='activitystream',
            name='o_auth2_access_token',
        ),
        migrations.RemoveField(
            model_name='activitystream',
            name='o_auth2_application',
        ),
        migrations.DeleteModel(
            name='OAuth2AccessToken',
        ),
        migrations.DeleteModel(
            name='OAuth2Application',
        ),
    ]
