# Generated by Django 4.2.16 on 2025-01-27 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0200_delete_token_cleanup_job'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventQuery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fqcn', models.CharField(max_length=255)),
                ('collection_version', models.CharField(max_length=32)),
                ('event_query', models.JSONField(default=dict)),
            ],
            options={
                'unique_together': {('fqcn', 'collection_version')},
            },
        ),
    ]
