# Generated by Django 4.2.16 on 2024-12-18 16:05

from django.db import migrations, models

from awx.main.migrations._create_system_jobs import delete_clear_tokens_sjt


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0200_alter_oauth2application_unique_together_and_more'),
    ]

    operations = [
        migrations.RunPython(delete_clear_tokens_sjt, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='systemjob',
            name='job_type',
            field=models.CharField(
                blank=True,
                choices=[
                    ('cleanup_jobs', 'Remove jobs older than a certain number of days'),
                    ('cleanup_activitystream', 'Remove activity stream entries older than a certain number of days'),
                    ('cleanup_sessions', 'Removes expired browser sessions from the database'),
                ],
                default='',
                max_length=32,
            ),
        ),
        migrations.AlterField(
            model_name='systemjobtemplate',
            name='job_type',
            field=models.CharField(
                blank=True,
                choices=[
                    ('cleanup_jobs', 'Remove jobs older than a certain number of days'),
                    ('cleanup_activitystream', 'Remove activity stream entries older than a certain number of days'),
                    ('cleanup_sessions', 'Removes expired browser sessions from the database'),
                ],
                default='',
                max_length=32,
            ),
        ),
    ]
