# Generated by Django 4.2.10 on 2024-09-16 10:22

from django.db import migrations, models

from awx.main.migrations._create_system_jobs import delete_clear_tokens_sjt


class Migration(migrations.Migration):
    dependencies = [
        ('main', '0201_create_managed_creds'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
        # Remove SSO app content
        # delete all sso application migrations
        migrations.RunSQL("DELETE FROM django_migrations WHERE app = 'sso';"),
        # delete all sso application content group permissions
        migrations.RunSQL(
            "DELETE FROM auth_group_permissions "
            "WHERE permission_id IN "
            "(SELECT id FROM auth_permission WHERE content_type_id in (SELECT id FROM django_content_type WHERE app_label = 'sso'));"
        ),
        # delete all sso application content permissions
        migrations.RunSQL("DELETE FROM auth_permission " "WHERE content_type_id IN (SELECT id FROM django_content_type WHERE app_label = 'sso');"),
        # delete sso application content type
        migrations.RunSQL("DELETE FROM django_content_type WHERE app_label = 'sso';"),
        # drop sso application created table
        migrations.RunSQL("DROP TABLE IF EXISTS sso_userenterpriseauth;"),
        # Alter inventory source source field
        migrations.AlterField(
            model_name='inventorysource',
            name='source',
            field=models.CharField(default=None, max_length=32),
        ),
        migrations.AlterField(
            model_name='inventoryupdate',
            name='source',
            field=models.CharField(default=None, max_length=32),
        ),
        # Alter OAuth2Application unique together
        migrations.AlterUniqueTogether(
            name='oauth2application',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='oauth2application',
            name='organization',
        ),
        migrations.RemoveField(
            model_name='oauth2application',
            name='user',
        ),
        migrations.RemoveField(
            model_name='activitystream',
            name='o_auth2_access_token',
        ),
        migrations.RemoveField(
            model_name='activitystream',
            name='o_auth2_application',
        ),
        migrations.DeleteModel(
            name='OAuth2AccessToken',
        ),
        migrations.DeleteModel(
            name='OAuth2Application',
        ),
        # Delete system token cleanup jobs, because tokens were deleted
        migrations.RunPython(delete_clear_tokens_sjt, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='systemjob',
            name='job_type',
            field=models.CharField(
                blank=True,
                choices=[
                    ('cleanup_jobs', 'Remove jobs older than a certain number of days'),
                    ('cleanup_activitystream', 'Remove activity stream entries older than a certain number of days'),
                    ('cleanup_sessions', 'Removes expired browser sessions from the database'),
                ],
                default='',
                max_length=32,
            ),
        ),
        migrations.AlterField(
            model_name='systemjobtemplate',
            name='job_type',
            field=models.CharField(
                blank=True,
                choices=[
                    ('cleanup_jobs', 'Remove jobs older than a certain number of days'),
                    ('cleanup_activitystream', 'Remove activity stream entries older than a certain number of days'),
                    ('cleanup_sessions', 'Removes expired browser sessions from the database'),
                ],
                default='',
                max_length=32,
            ),
        ),
    ]
