# Generated by Django 4.2.10 on 2024-09-16 10:22
from django.db import migrations, models
from awx.main.migrations._create_system_jobs import delete_clear_tokens_sjt


# --- START of function merged from 0203_rename_github_app_kind.py ---
def update_github_app_kind(apps, schema_editor):
    """
    Updates the 'kind' field for CredentialType records
    from 'github_app' to 'github_app_lookup'.
    This addresses a change in the entry point key for the GitHub App plugin.
    """
    CredentialType = apps.get_model('main', 'CredentialType')
    db_alias = schema_editor.connection.alias
    CredentialType.objects.using(db_alias).filter(kind='github_app').update(kind='github_app_lookup')


# --- END of function merged from 0203_rename_github_app_kind.py ---


class Migration(migrations.Migration):
    dependencies = [
        ('main', '0201_create_managed_creds'),
    ]
    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
        # Remove SSO app content
        # delete all sso application migrations
        # Added reverse_sql=migrations.RunSQL.noop to make this reversible for tests
        migrations.RunSQL("DELETE FROM django_migrations WHERE app = 'sso';", reverse_sql=migrations.RunSQL.noop),
        # delete all sso application content group permissions
        # Added reverse_sql=migrations.RunSQL.noop to make this reversible for tests
        migrations.RunSQL(
            "DELETE FROM auth_group_permissions "
            "WHERE permission_id IN "
            "(SELECT id FROM auth_permission WHERE content_type_id in (SELECT id FROM django_content_type WHERE app_label = 'sso'));",
            reverse_sql=migrations.RunSQL.noop,
        ),
        # delete all sso application content permissions
        # Added reverse_sql=migrations.RunSQL.noop to make this reversible for tests
        migrations.RunSQL(
            "DELETE FROM auth_permission " "WHERE content_type_id IN (SELECT id FROM django_content_type WHERE app_label = 'sso');",
            reverse_sql=migrations.RunSQL.noop,
        ),
        # delete sso application content type
        # Added reverse_sql=migrations.RunSQL.noop to make this reversible for tests
        migrations.RunSQL("DELETE FROM django_content_type WHERE app_label = 'sso';", reverse_sql=migrations.RunSQL.noop),
        # drop sso application created table
        # Added reverse_sql=migrations.RunSQL.noop to make this reversible for tests
        migrations.RunSQL("DROP TABLE IF EXISTS sso_userenterpriseauth;", reverse_sql=migrations.RunSQL.noop),
        # Alter inventory source source field
        migrations.AlterField(
            model_name='inventorysource',
            name='source',
            field=models.CharField(default=None, max_length=32),
        ),
        migrations.AlterField(
            model_name='inventoryupdate',
            name='source',
            field=models.CharField(default=None, max_length=32),
        ),
        # Alter OAuth2Application unique together
        migrations.AlterUniqueTogether(
            name='oauth2application',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='oauth2application',
            name='organization',
        ),
        migrations.RemoveField(
            model_name='oauth2application',
            name='user',
        ),
        migrations.RemoveField(
            model_name='activitystream',
            name='o_auth2_access_token',
        ),
        migrations.RemoveField(
            model_name='activitystream',
            name='o_auth2_application',
        ),
        migrations.DeleteModel(
            name='OAuth2AccessToken',
        ),
        migrations.DeleteModel(
            name='OAuth2Application',
        ),
        # Delete system token cleanup jobs, because tokens were deleted
        migrations.RunPython(delete_clear_tokens_sjt, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='systemjob',
            name='job_type',
            field=models.CharField(
                blank=True,
                choices=[
                    ('cleanup_jobs', 'Remove jobs older than a certain number of days'),
                    ('cleanup_activitystream', 'Remove activity stream entries older than a certain number of days'),
                    ('cleanup_sessions', 'Removes expired browser sessions from the database'),
                ],
                default='',
                max_length=32,
            ),
        ),
        migrations.AlterField(
            model_name='systemjobtemplate',
            name='job_type',
            field=models.CharField(
                blank=True,
                choices=[
                    ('cleanup_jobs', 'Remove jobs older than a certain number of days'),
                    ('cleanup_activitystream', 'Remove activity stream entries older than a certain number of days'),
                    ('cleanup_sessions', 'Removes expired browser sessions from the database'),
                ],
                default='',
                max_length=32,
            ),
        ),
        # --- START of operations merged from 0203_rename_github_app_kind.py ---
        migrations.RunPython(update_github_app_kind, migrations.RunPython.noop),
        # --- END of operations merged from 0203_rename_github_app_kind.py ---
    ]
