# Generated by Django 4.2.16 on 2025-03-11 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0201_delete_token_cleanup_job'),
    ]

    operations = [
        migrations.AddField(
            model_name='unifiedjob',
            name='priority',
            field=models.PositiveIntegerField(
                default=0,
                editable=False,
                help_text='Relative priority to other jobs. The higher the number, the higher the priority. Jobs with equivalent prioirty are started based on available capacity and launch time.',
            ),
        ),
        migrations.AddField(
            model_name='unifiedjobtemplate',
            name='priority',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
