# Generated by Django 4.2.16 on 2025-01-29 12:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0201_eventquery'),
    ]

    operations = [
        migrations.CreateModel(
            name='IndirectManagedNodeAudit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=255)),
                ('canonical_facts', models.JSONField(default=dict)),
                ('facts', models.JSONField(default=dict)),
                ('events', models.JSONField(default=list)),
                ('count', models.PositiveIntegerField(default=0)),
                (
                    'host',
                    models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='host_indirect_host_audits', to='main.host'),
                ),
                (
                    'inventory',
                    models.ForeignKey(
                        null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='inventory_indirect_host_audits', to='main.inventory'
                    ),
                ),
                (
                    'job',
                    models.ForeignKey(editable=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='job_indirect_host_audits', to='main.job'),
                ),
                (
                    'organization',
                    models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='organization_indirect_host_audits', to='main.organization'),
                ),
            ],
            options={
                'unique_together': {('name', 'job')},
            },
        ),
    ]
