# Generated by Django 4.2.20 on 2025-04-17 17:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0202_delete_token_cleanup_job'),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryGroupVariablesWithHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_name', models.CharField(max_length=256)),
                ('variables', models.JSONField()),
                (
                    'inventory',
                    models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inventory_group_variables', to='main.inventory'),
                ),
            ],
        ),
    ]
