# Generated by Django 4.2.20 on 2025-04-22 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0202_delete_token_cleanup_job'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='unifiedjobtemplate',
            constraint=models.UniqueConstraint(fields=('polymorphic_ctype', 'name', 'organization'), name='ujt_hard_name_constraint'),
        ),
    ]
