# Generated by Django 4.2.16 on 2025-04-11 12:09

import awx.main.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0202_delete_token_cleanup_job'),
    ]

    operations = [
        migrations.AddField(
            model_name='workflowjob',
            name='ask_nodes_job_type_on_launch',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='workflowjob',
            name='nodes_job_type',
            field=models.CharField(blank=True, choices=[('run', 'Run'), ('check', 'Check')], default='', max_length=32),
        ),
        migrations.AddField(
            model_name='workflowjobtemplate',
            name='ask_nodes_job_type_on_launch',
            field=awx.main.fields.AskForField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='workflowjobtemplate',
            name='nodes_job_type',
            field=models.CharField(blank=True, choices=[('run', 'Run'), ('check', 'Check')], default='', max_length=32),
        ),
    ]
