# Generated by Django 4.2.20 on 2025-04-16 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0202_delete_token_cleanup_job'),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryGroupVariablesWithHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_name', models.CharField(max_length=256)),
                ('variables', models.JSONField()),
            ],
        ),
    ]
