# Generated by Django 4.2.16 on 2025-01-29 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0202_indirectmanagednodeaudit'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='event_queries_processed',
            field=models.BooleanField(default=False, help_text='Events of this job have been queried for indirect host information'),
        ),
    ]
