# Generated by Django 4.2.21 on 2025-07-18 20:19

from django.db import migrations


def update_github_app_kind(apps, schema_editor):
    """
    Updates the 'kind' field for CredentialType records
    from 'github_app' to 'github_app_lookup'.
    This addresses a change in the entry point key for the GitHub App plugin.
    """
    CredentialType = apps.get_model('main', 'CredentialType')
    db_alias = schema_editor.connection.alias

    CredentialType.objects.using(db_alias).filter(kind='github_app').update(kind='github_app_lookup')


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0202_squashed_deletions'),
    ]

    operations = [
        migrations.RunPython(update_github_app_kind, migrations.RunPython.noop),
    ]
