# Generated by Django migration for converting Controller role definitions

from django.db import migrations
from ansible_base.rbac.migrations._utils import give_permissions


def convert_controller_role_definitions(apps, schema_editor):
    """
    Convert Controller role definitions to regular role definitions:
    - Controller Organization Admin -> Organization Admin
    - Controller Organization Member -> Organization Member
    - Controller Team Admin -> Team Admin
    - Controller Team Member -> Team Member

    Then delete the old Controller role definitions.
    """
    RoleDefinition = apps.get_model('dab_rbac', 'RoleDefinition')
    RoleUserAssignment = apps.get_model('dab_rbac', 'RoleUserAssignment')
    RoleTeamAssignment = apps.get_model('dab_rbac', 'RoleTeamAssignment')

    # Mapping of old Controller role names to new role names
    role_mappings = {
        'Controller Organization Admin': 'Organization Admin',
        'Controller Organization Member': 'Organization Member',
        'Controller Team Admin': 'Team Admin',
        'Controller Team Member': 'Team Member',
    }

    for old_name, new_name in role_mappings.items():
        # Find the old Controller role definition
        old_role = RoleDefinition.objects.filter(name=old_name).first()
        if not old_role:
            continue  # Skip if the old role doesn't exist

        # Find or create the new role definition with the same permissions
        new_role, created = RoleDefinition.objects.get_or_create(
            name=new_name,
            defaults={
                'description': old_role.description.replace('Controller ', '') if old_role.description else '',
                'managed': old_role.managed,
                'content_type': old_role.content_type,
            },
        )

        # If we created a new role, copy the permissions
        if created:
            new_role.permissions.set(old_role.permissions.all())

        # Collect all the assignments that need to be migrated
        # Group by object (content_type + object_id) to batch the give_permissions calls
        assignments_by_object = {}

        # Get user assignments
        user_assignments = RoleUserAssignment.objects.filter(role_definition=old_role).select_related('object_role')
        for assignment in user_assignments:
            key = (assignment.object_role.content_type_id, assignment.object_role.object_id)
            if key not in assignments_by_object:
                assignments_by_object[key] = {'users': [], 'teams': []}
            assignments_by_object[key]['users'].append(assignment.user)

        # Get team assignments
        team_assignments = RoleTeamAssignment.objects.filter(role_definition=old_role).select_related('object_role')
        for assignment in team_assignments:
            key = (assignment.object_role.content_type_id, assignment.object_role.object_id)
            if key not in assignments_by_object:
                assignments_by_object[key] = {'users': [], 'teams': []}
            assignments_by_object[key]['teams'].append(assignment.team.id)

        # Use give_permissions to create new assignments with the new role definition
        for (content_type_id, object_id), data in assignments_by_object.items():
            if data['users'] or data['teams']:
                give_permissions(
                    apps,
                    new_role,
                    users=data['users'],
                    teams=data['teams'],
                    object_id=object_id,
                    content_type_id=content_type_id,
                )

        # Delete the old role definition (this will cascade to delete old assignments and ObjectRoles)
        old_role.delete()

    # rename Controller System Auditor to Platform Auditor
    RoleDefinition.objects.filter(name='Controller System Auditor').update(name='Platform Auditor')


def reverse_convert_controller_role_definitions(apps, schema_editor):
    """
    Reverse the conversion of Controller role definitions to platform role definitions.
    """
    RoleDefinition = apps.get_model('dab_rbac', 'RoleDefinition')
    RoleUserAssignment = apps.get_model('dab_rbac', 'RoleUserAssignment')
    RoleTeamAssignment = apps.get_model('dab_rbac', 'RoleTeamAssignment')
    role_mappings = {
        'Controller Organization Admin': 'Organization Admin',
        'Controller Organization Member': 'Organization Member',
        'Controller Team Admin': 'Team Admin',
        'Controller Team Member': 'Team Member',
    }

    for _, new_name in role_mappings.items():
        RoleUserAssignment.objects.filter(role_definition__name=new_name).delete()
        RoleTeamAssignment.objects.filter(role_definition__name=new_name).delete()

    # rename Platform Auditor to Controller System Auditor
    RoleDefinition.objects.filter(name='Platform Auditor').update(name='Controller System Auditor')


class Migration(migrations.Migration):
    dependencies = [
        ('main', '0202_squashed_deletions'),
    ]

    operations = [
        migrations.RunPython(
            convert_controller_role_definitions,
            reverse_convert_controller_role_definitions,
        ),
    ]
