# Generated by Django 4.2.20 on 2025-04-22 15:54

import logging

from django.db import migrations, models

from django.db.models import Count


logger = logging.getLogger(__name__)


def _rename_duplicates(cls):
    for organization_id in cls.objects.order_by().values_list('organization_id', flat=True).distinct():
        duplicate_data = cls.objects.values('name').filter(organization_id=organization_id).annotate(count=Count('name')).order_by().filter(count__gt=1)
        for data in duplicate_data:
            name = data['name']
            ct = 0
            for ujt in cls.objects.filter(name=name):
                ct += 1
                ujt.name = ujt.name + f'_dup{ct}'
                logger.info(f'Renaming duplicate {cls._meta.model_name} to `{ujt.name}` because of duplicate name entry')
                ujt.save(update_fields=['name'])


def rename_jts(apps, schema_editor):
    cls = apps.get_model('main', 'JobTemplate')
    _rename_duplicates(cls)


def rename_projects(apps, schema_editor):
    cls = apps.get_model('main', 'Project')
    _rename_duplicates(cls)


def change_inventory_source_org_unique(apps, schema_editor):
    cls = apps.get_model('main', 'InventorySource')
    r = cls.objects.update(org_unique=False)
    logger.info(f'Set database constraint rule for {r} inventory source objects')


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0202_delete_token_cleanup_job'),
    ]

    operations = [
        migrations.RunPython(rename_jts, migrations.RunPython.noop),
        migrations.RunPython(rename_projects, migrations.RunPython.noop),
        migrations.AddField(
            model_name='unifiedjobtemplate',
            name='org_unique',
            field=models.BooleanField(blank=True, default=True, editable=False, help_text='Used internally to selectively enforce database constraint on name'),
        ),
        migrations.RunPython(change_inventory_source_org_unique, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name='unifiedjobtemplate',
            constraint=models.UniqueConstraint(
                condition=models.Q(('org_unique', True)), fields=('polymorphic_ctype', 'name', 'organization'), name='ujt_hard_name_constraint'
            ),
        ),
    ]
