# Generated by Django 4.2.21 on 2025-10-14 13:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0204_squashed_deletions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='credentialinputsource',
            name='input_field_name',
            field=models.CharField(default=None, max_length=1024),
        ),
        migrations.AlterField(
            model_name='credentialinputsource',
            name='source_credential',
            field=models.ForeignKey(
                default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='target_input_sources', to='main.credential'
            ),
        ),
        migrations.AlterField(
            model_name='credentialinputsource',
            name='target_credential',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='input_sources', to='main.credential'),
        ),
    ]
