# Generated by Django 5.2.8 on 2026-02-20 03:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0204_squashed_deletions'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='instancegroup',
            options={
                'default_permissions': ('change', 'delete', 'view'),
                'ordering': ('pk',),
                'permissions': [('use_instancegroup', 'Can use instance group in a preference list of a resource')],
            },
        ),
        migrations.AlterModelOptions(
            name='workflowjobnode',
            options={'ordering': ('pk',)},
        ),
        migrations.AlterModelOptions(
            name='workflowjobtemplatenode',
            options={'ordering': ('pk',)},
        ),
    ]
