# Generated by Django 5.2.8 on 2025-11-20 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0204_squashed_deletions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instance',
            name='peers',
            field=models.ManyToManyField(
                related_name='peers_from', through='main.InstanceLink', through_fields=('source', 'target'), to='main.receptoraddress'
            ),
        ),
        migrations.AlterField(
            model_name='job',
            name='hosts',
            field=models.ManyToManyField(editable=False, related_name='jobs', through='main.JobHostSummary', through_fields=('job', 'host'), to='main.host'),
        ),
        migrations.AlterField(
            model_name='role',
            name='ancestors',
            field=models.ManyToManyField(
                related_name='descendents', through='main.RoleAncestorEntry', through_fields=('descendent', 'ancestor'), to='main.role'
            ),
        ),
    ]
