# Generated by Django 4.2.20 on 2025-05-22 08:57

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0205_delete_token_cleanup_job'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instance',
            name='capacity_adjustment',
            field=models.DecimalField(
                decimal_places=2, default=Decimal('0.75'), max_digits=3, validators=[django.core.validators.MinValueValidator(Decimal('0'))]
            ),
        ),
    ]
