# Generated by Django 5.2.8 on 2026-07-20 11:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('main', '0208_cleanup_orphaned_token_schedules'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='skip_tags',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='jobtemplate',
            name='skip_tags',
            field=models.TextField(blank=True, default=''),
        ),
    ]
