[pytest]
DJANGO_SETTINGS_MODULE = awx.main.tests.settings_for_test
python_files = *.py
addopts = --reuse-db --nomigrations --tb=native
markers =
    ac: access control test
    survey: tests related to survey feature
    inventory_import: tests of code used by inventory import command
    defined_in_file:
    job_permissions:
    activity_stream_access:
    job_runtime_vars:
    fixture_args:

filterwarnings =
  error

  # FIXME: Upgrade python-dateutil https://github.com/dateutil/dateutil/issues/1340
  once:datetime.datetime.utcfromtimestamp\(\) is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC:DeprecationWarning

  # NOTE: the following are present using python 3.11
  # FIXME: Delete this entry once `pyparsing` is updated.
  once:module 'sre_constants' is deprecated:DeprecationWarning:_pytest.assertion.rewrite

  # FIXME: Delete this entry once `polymorphic` is updated.
  once:pkg_resources is deprecated as an API.

  # FIXME: Delete this entry once `zope` is updated.
  once:Deprecated call to `pkg_resources.declare_namespace.'zope'.`.\nImplementing implicit namespace packages .as specified in PEP 420. is preferred to `pkg_resources.declare_namespace`. See https.//setuptools.pypa.io/en/latest/references/keywords.html#keyword-namespace-packages:DeprecationWarning:

  # FIXME: Delete this entry once the deprecation is acted upon.
  # Note: RemovedInDjango51Warning may not exist in newer Django versions
  ignore:'index_together' is deprecated. Use 'Meta.indexes' in 'main.\w+' instead.

  # FIXME: Add ordering to Resource model in django-ansible-base and delete this entry.
  once:Pagination may yield inconsistent results with an unordered object_list.*Resource:django.core.paginator.UnorderedObjectListWarning

# https://docs.pytest.org/en/stable/usage.html#creating-junitxml-format-files
junit_duration_report = call
# xunit1 contains more metadata than xunit2 so it's better for CI UIs:
junit_family = xunit1
junit_logging = all
junit_log_passing_tests = true
junit_suite_name = awx_test_suite
