[metadata]
name = awx
author = Red Hat
author_email = info@ansible.com
version = attr: awx.get_version

[options]
packages =
    awx
zip_safe = False
include_package_data = True

[options.entry_points]
console_scripts =
    awx-manage = awx:manage
awx_plugins.managed_credentials =
    akeyless = awx.main.credential_plugins.akeyless:akeyless_plugin
    akeyless_ssh = awx.main.credential_plugins.akeyless:akeyless_ssh_plugin