#!/usr/bin/env bash

# Enable AWX virtualenv
for venv_path in /var/lib/awx/venv/awx; do
  if [ -f $venv_path/bin/activate ]; then
    . $venv_path/bin/activate
  fi
done

# Run the requested Python command, using the interpreter from the path
exec python3 "$@"
