#!/bin/bash

# Enable needed Software Collections, if installed
for scl in rh-python36; do
  if [ -f /etc/scl/prefixes/$scl ]; then
    if [ -f `cat /etc/scl/prefixes/$scl`/$scl/enable ]; then
      . `cat /etc/scl/prefixes/$scl`/$scl/enable
    fi
  fi
done

# Enable Tower virtualenv
if [ -f /var/lib/awx/venv/awx/bin/activate ]; then
  . /var/lib/awx/venv/awx/bin/activate
fi

# Run the requested Python command, using the interpreter from the path
exec python3 "$@"
