#!/usr/bin/awx-python
import sys
import os
import signal

def write_stdout(s):
    sys.stdout.write(s)
    sys.stdout.flush()

def write_stderr(s):
    sys.stderr.write(s)
    sys.stderr.flush()

def main():
    while 1:
        write_stdout('READY\n')
        line = sys.stdin.readline()
        headers = dict([ x.split(':') for x in line.split() ])
        headers.update(dict([ x.split(':') for x in sys.stdin.read(int(headers['len'])).split()]))
        if headers['eventname'] == 'PROCESS_STATE_FATAL':
            os.kill(os.getppid(), signal.SIGTERM)
        write_stdout('RESULT 2\nOK')

if __name__ == "__main__":
    main()
