#!/bin/bash

# Enable Tower virtualenv
if [ -f /var/lib/awx/venv/tower/bin/activate ]; then
  . /var/lib/awx/venv/tower/bin/activate
fi

# Run the requested Python command, using the interpreter from the path
exec python "$@"
