---
- name: Template the collection galaxy.yml
  hosts: localhost
  gather_facts: false
  connection: local
  vars:
    collection_version: 0.0.1  # not for updating, pass in extra_vars
    collection_source: "{{ playbook_dir }}/../"
    collection_path: "{{ playbook_dir }}/../../awx_collection_build"
  pre_tasks:
    - file:
        path: "{{ collection_path }}"
        state: absent

    - copy:
        src: "{{ collection_source }}"
        dest: "{{ collection_path }}"
        remote_src: true

  roles:
    - template_galaxy

  tasks: []
