# Generated by Django 2.2.11 on 2020-08-04 15:19

import logging

from django.db import migrations, models

from awx.conf.migrations import _subscriptions as subscriptions

logger = logging.getLogger('awx.conf.migrations')


class Migration(migrations.Migration):

    dependencies = [
        ('conf', '0007_v380_rename_more_settings'),
    ]

    operations = [
        migrations.RunPython(subscriptions.clear_old_license),
    ]
