# Generated by Django 4.2 on 2023-06-09 19:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('conf', '0009_rename_proot_settings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='setting',
            name='value',
            field=models.JSONField(null=True),
        ),
    ]
