# Generated by Django 4.2 on 2023-05-22 16:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('conf', '0009_rename_proot_settings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='setting',
            name='created',
            field=models.DateTimeField(default=None, editable=False, help_text='Timestamp of when this resource was created.'),
        ),
        migrations.AlterField(
            model_name='setting',
            name='modified',
            field=models.DateTimeField(default=None, editable=False, help_text='Timestamp of last user modification of any fields or related objects.'),
        ),
    ]
