# Generated by Django 4.2.3 on 2023-09-01 14:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('conf', '0010_change_to_JSONField'),
    ]

    operations = [
        migrations.AlterField(
            model_name='setting',
            name='created',
            field=models.DateTimeField(default=None, editable=False, help_text='Timestamp of when this resource was created.'),
        ),
        migrations.AlterField(
            model_name='setting',
            name='modified',
            field=models.DateTimeField(default=None, editable=False, help_text='Timestamp of last user modification of any fields or related objects.'),
        ),
    ]
