# Generated by Django 4.2.10 on 2024-08-27 19:31

from django.db import migrations

OIDC_AUTH_CONF_KEYS = ['SOCIAL_AUTH_OIDC_KEY', 'SOCIAL_AUTH_OIDC_SECRET', 'SOCIAL_AUTH_OIDC_OIDC_ENDPOINT', 'SOCIAL_AUTH_OIDC_VERIFY_SSL']


def remove_oidc_auth_conf(apps, scheme_editor):
    setting = apps.get_model('conf', 'Setting')
    setting.objects.filter(key__in=OIDC_AUTH_CONF_KEYS).delete()


class Migration(migrations.Migration):
    dependencies = [
        ('conf', '0011_remove_ldap_auth_conf'),
    ]

    operations = [
        migrations.RunPython(remove_oidc_auth_conf),
    ]
