---
services:
  awx_1:
    depends_on:
      - hashivault
      - conjur

  hashivault:
    image: hashicorp/vault:1.14
    container_name: tools_hashivault_1
    networks:
      - awx
    ports:
      - "8200:8200"
    cap_add:
      - IPC_LOCK
    environment:
      VAULT_DEV_ROOT_TOKEN_ID: "vaultdev"

  conjur:
    image: cyberark/conjur
    container_name: tools_conjur_1
    command: server -p 8300
    networks:
      - awx
    environment:
      DATABASE_URL: postgres://awx@postgres/postgres
      # nosec: dev-only data encryption key for local Conjur container
      CONJUR_DATA_KEY: "dveUwOI/71x9BPJkIgvQRRBF3SdASc+HP4CUGL7TKvM="
    depends_on:
      - postgres
    ports:
      - "8300:8300"
