nginx:          make nginx
runworker:      make runworker
daphne:         make daphne
celeryd:        make celeryd
receiver:       make receiver
flower:         make flower
uwsgi:          make uwsgi
