nginx:          make nginx
runworker:      make runworker
daphne:         make daphne
dispatcher:     make dispatcher
receiver:       make receiver
uwsgi:          make uwsgi
jupyter:        make jupyter
