"""Functional tests for start_fact_cache / finish_fact_cache.

These tests use real database objects (via pytest-django) and real files
on disk, but do not launch jobs or subprocesses.  Fact files are written
by start_fact_cache and then manipulated to simulate ansible output
before calling finish_fact_cache.

Generated by Claude Opus 4.6 (claude-opus-4-6).
"""

import json
import os
import time
from datetime import timedelta

import pytest

from django.utils.timezone import now

from awx.main.models import Host, Inventory
from awx.main.tasks.facts import start_fact_cache, finish_fact_cache


@pytest.fixture
def artifacts_dir(tmp_path):
    d = tmp_path / 'artifacts'
    d.mkdir()
    return str(d)


@pytest.mark.django_db
class TestFinishFactCacheScoping:
    """finish_fact_cache must only update hosts matched by the provided queryset."""

    def test_same_hostname_different_inventories(self, organization, artifacts_dir):
        """Two inventories share a hostname; only the targeted one should be updated.

        Generated by Claude Opus 4.6 (claude-opus-4-6).
        """
        inv1 = Inventory.objects.create(organization=organization, name='scope-inv1')
        inv2 = Inventory.objects.create(organization=organization, name='scope-inv2')

        host1 = inv1.hosts.create(name='shared')
        host2 = inv2.hosts.create(name='shared')

        # Give both hosts initial facts
        for h in (host1, host2):
            h.ansible_facts = {'original': True}
            h.ansible_facts_modified = now()
            h.save(update_fields=['ansible_facts', 'ansible_facts_modified'])

        # start_fact_cache writes reference files for inv1's hosts
        start_fact_cache(inv1.hosts.all(), artifacts_dir=artifacts_dir, timeout=0, inventory_id=inv1.id)

        # Simulate ansible writing new facts for 'shared'
        fact_file = os.path.join(artifacts_dir, 'fact_cache', 'shared')
        future = time.time() + 60
        with open(fact_file, 'w') as f:
            json.dump({'updated': True}, f)
        os.utime(fact_file, (future, future))

        # finish with inv1's hosts as the queryset
        finish_fact_cache(inv1.hosts, artifacts_dir=artifacts_dir, inventory_id=inv1.id)

        host1.refresh_from_db()
        host2.refresh_from_db()

        assert host1.ansible_facts == {'updated': True}
        assert host2.ansible_facts == {'original': True}, 'Host in a different inventory was modified despite not being in the queryset'


@pytest.mark.django_db
class TestFinishFactCacheConcurrentProtection:
    """finish_fact_cache must not clear facts that a concurrent job updated."""

    def test_no_clear_when_no_file_was_written(self, organization, artifacts_dir):
        """Host with no prior facts should not have facts cleared when file is missing.

        Generated by Claude Opus 4.6 (claude-opus-4-6).

        start_fact_cache records hosts_cached[host] = False for hosts with no
        prior facts (no file written).  finish_fact_cache should skip the clear
        for these hosts because the missing file is expected, not a clear signal.
        """
        inv = Inventory.objects.create(organization=organization, name='concurrent-inv')
        host = inv.hosts.create(name='target')

        job_created = now() - timedelta(minutes=5)

        # start_fact_cache records host with False (no facts → no file written)
        start_fact_cache(inv.hosts.all(), artifacts_dir=artifacts_dir, timeout=0, inventory_id=inv.id)

        # Simulate a concurrent job updating this host's facts AFTER our job was created
        host.ansible_facts = {'from_concurrent_job': True}
        host.ansible_facts_modified = now()
        host.save(update_fields=['ansible_facts', 'ansible_facts_modified'])

        # The fact file is missing because start_fact_cache never wrote one.
        # finish_fact_cache should skip this host entirely.
        finish_fact_cache(
            inv.hosts,
            artifacts_dir=artifacts_dir,
            inventory_id=inv.id,
            job_created=job_created,
        )

        host.refresh_from_db()
        assert host.ansible_facts == {'from_concurrent_job': True}, 'Facts were cleared for a host that never had a fact file written'

    def test_skip_clear_when_facts_modified_after_job_created(self, organization, artifacts_dir):
        """If a file was written and then deleted, but facts were concurrently updated, skip clear.

        Generated by Claude Opus 4.6 (claude-opus-4-6).
        """
        inv = Inventory.objects.create(organization=organization, name='concurrent-written-inv')
        host = inv.hosts.create(name='target')

        old_time = now() - timedelta(hours=1)
        host.ansible_facts = {'original': True}
        host.ansible_facts_modified = old_time
        host.save(update_fields=['ansible_facts', 'ansible_facts_modified'])

        job_created = now() - timedelta(minutes=5)

        # start_fact_cache writes a file (host has facts → True in map)
        start_fact_cache(inv.hosts.all(), artifacts_dir=artifacts_dir, timeout=0, inventory_id=inv.id)

        # Remove the fact file (ansible didn't target this host via --limit)
        os.remove(os.path.join(artifacts_dir, 'fact_cache', host.name))

        # Simulate a concurrent job updating this host's facts AFTER our job was created
        host.ansible_facts = {'from_concurrent_job': True}
        host.ansible_facts_modified = now()
        host.save(update_fields=['ansible_facts', 'ansible_facts_modified'])

        finish_fact_cache(
            inv.hosts,
            artifacts_dir=artifacts_dir,
            inventory_id=inv.id,
            job_created=job_created,
        )

        host.refresh_from_db()
        assert host.ansible_facts == {'from_concurrent_job': True}, 'Facts set by a concurrent job were cleared despite ansible_facts_modified > job_created'

    def test_clear_when_facts_predate_job(self, organization, artifacts_dir):
        """If facts predate the job, a missing file should still clear them.

        Generated by Claude Opus 4.6 (claude-opus-4-6).
        """
        inv = Inventory.objects.create(organization=organization, name='clear-inv')
        host = inv.hosts.create(name='stale')

        old_time = now() - timedelta(hours=1)
        host.ansible_facts = {'stale': True}
        host.ansible_facts_modified = old_time
        host.save(update_fields=['ansible_facts', 'ansible_facts_modified'])

        job_created = now() - timedelta(minutes=5)

        start_fact_cache(inv.hosts.all(), artifacts_dir=artifacts_dir, timeout=0, inventory_id=inv.id)

        # Remove the fact file to simulate ansible's clear_facts
        os.remove(os.path.join(artifacts_dir, 'fact_cache', host.name))

        finish_fact_cache(
            inv.hosts,
            artifacts_dir=artifacts_dir,
            inventory_id=inv.id,
            job_created=job_created,
        )

        host.refresh_from_db()
        assert host.ansible_facts == {}, 'Stale facts should have been cleared when the fact file is missing ' 'and ansible_facts_modified predates job_created'


@pytest.mark.django_db
class TestConstructedInventoryFactCache:
    """finish_fact_cache with a constructed inventory queryset must target source hosts."""

    def test_facts_resolve_to_source_host(self, organization, artifacts_dir):
        """Facts must be written to the source host, not the constructed copy.

        Generated by Claude Opus 4.6 (claude-opus-4-6).
        """
        from django.db.models.functions import Cast

        inv_input = Inventory.objects.create(organization=organization, name='ci-input')
        source_host = inv_input.hosts.create(name='webserver')

        inv_constructed = Inventory.objects.create(organization=organization, name='ci-constructed', kind='constructed')
        inv_constructed.input_inventories.add(inv_input)
        constructed_host = Host.objects.create(
            inventory=inv_constructed,
            name='webserver',
            instance_id=str(source_host.id),
        )

        # Build the same queryset that get_hosts_for_fact_cache uses
        id_field = Host._meta.get_field('id')
        source_qs = Host.objects.filter(id__in=inv_constructed.hosts.exclude(instance_id='').values_list(Cast('instance_id', output_field=id_field)))

        # Give the source host initial facts so start_fact_cache writes a file
        source_host.ansible_facts = {'role': 'web'}
        source_host.ansible_facts_modified = now()
        source_host.save(update_fields=['ansible_facts', 'ansible_facts_modified'])

        start_fact_cache(source_qs, artifacts_dir=artifacts_dir, timeout=0, inventory_id=inv_constructed.id)

        # Simulate ansible writing updated facts
        fact_file = os.path.join(artifacts_dir, 'fact_cache', 'webserver')
        future = time.time() + 60
        with open(fact_file, 'w') as f:
            json.dump({'role': 'web', 'deployed': True}, f)
        os.utime(fact_file, (future, future))

        finish_fact_cache(source_qs, artifacts_dir=artifacts_dir, inventory_id=inv_constructed.id)

        source_host.refresh_from_db()
        constructed_host.refresh_from_db()

        assert source_host.ansible_facts == {'role': 'web', 'deployed': True}
        assert not constructed_host.ansible_facts, f'Facts were stored on the constructed host: {constructed_host.ansible_facts!r}'
