# Test file for cancel + dependency chain behavior
# Generated by Claude Opus 4.6 (claude-opus-4-6)
#
# These tests verify behavior when canceling jobs that have dependency chain
# project updates (created by DependencyManager for projects with
# scm_update_on_launch=True).
#
# Fixes verified:
#
# 1. Job.get_jobs_fail_chain() now includes dependent_jobs M2M entries,
#    so cancel propagates forward from a job to its dependency updates.
#
# 2. TaskManager.process_job_dep_failures() now checks for "canceled" in
#    addition to ("error", "failed"), so a canceled dependency causes the
#    blocked job to be failed.

import pytest
from unittest import mock

from awx.api.versioning import reverse
from awx.main.scheduler import TaskManager, DependencyManager
from awx.main.models import Job, Project, Inventory, JobTemplate, ProjectUpdate
from . import create_job


@pytest.mark.django_db
class TestCancelPropagatesToDependency:
    """When a job is canceled, its dependency project updates (linked via
    dependent_jobs M2M) should also be canceled."""

    def test_cancel_job_cancels_dependency_project_update(self, controlplane_instance_group, job_template_factory, mocker):
        """Set up a job with a dependency project update (via DependencyManager),
        then cancel the job, and verify that the dependency project update
        also gets canceled."""
        objects = job_template_factory(
            'jt',
            organization='org1',
            project='proj',
            inventory='inv',
            credential='cred',
        )
        p = objects.project
        p.scm_update_on_launch = True
        p.scm_update_cache_timeout = 0
        p.scm_type = "git"
        p.scm_url = "http://github.com/ansible/ansible.git"
        p.save(skip_update=True)

        j = create_job(objects.job_template, dependencies_processed=False)

        # Run DependencyManager to create the project update dependency
        with mock.patch('awx.main.models.unified_jobs.UnifiedJobTemplate.update'):
            DependencyManager().schedule()

        # Verify dependency was created
        assert j.dependent_jobs.count() == 1
        pu = j.dependent_jobs.first()
        assert isinstance(pu.get_real_instance(), ProjectUpdate)

        # Simulate the project update is now running
        ProjectUpdate.objects.filter(pk=pu.pk).update(
            status='running',
            celery_task_id='fake-task-id',
            controller_node='test-node',
        )
        pu.refresh_from_db()
        assert pu.status == 'running'

        # Cancel the job
        j.refresh_from_db()
        assert j.can_cancel
        with mock.patch('awx.main.models.unified_jobs.UnifiedJob.cancel_dispatcher_process'):
            j.cancel()

        j.refresh_from_db()
        pu.refresh_from_db()

        assert j.cancel_flag is True
        # Cancel now propagates to the dependency project update via
        # get_jobs_fail_chain() including dependent_jobs M2M entries
        assert pu.cancel_flag is True

    def test_get_jobs_fail_chain_includes_dependent_jobs(self, controlplane_instance_group, job_template_factory):
        """Verify that Job.get_jobs_fail_chain() includes entries
        from the dependent_jobs M2M relationship."""
        objects = job_template_factory(
            'jt',
            organization='org1',
            project='proj',
            inventory='inv',
            credential='cred',
        )
        p = objects.project
        p.scm_update_on_launch = True
        p.scm_update_cache_timeout = 0
        p.scm_type = "git"
        p.scm_url = "http://github.com/ansible/ansible.git"
        p.save(skip_update=True)

        j = create_job(objects.job_template, dependencies_processed=False)

        with mock.patch('awx.main.models.unified_jobs.UnifiedJobTemplate.update'):
            DependencyManager().schedule()

        assert j.dependent_jobs.count() == 1
        pu = j.dependent_jobs.first()

        # project_update FK is not set (only set by the runner during pre_run_hook)
        assert j.project_update_id is None

        # The fail chain includes the dependent_jobs M2M entries
        chain = j.get_jobs_fail_chain()
        assert pu in chain


@pytest.mark.django_db
class TestCanceledDependencyFailsBlockedJob:
    """When a dependency project update is canceled, the task manager should
    fail the blocked job via process_job_dep_failures."""

    def test_canceled_dependency_fails_blocked_job(self, controlplane_instance_group, job_template_factory, mocker):
        """Set up a job blocked by a dependency project update, then mark the
        dependency as canceled. Run the task manager and verify the blocked
        job is failed."""
        objects = job_template_factory(
            'jt',
            organization='org1',
            project='proj',
            inventory='inv',
            credential='cred',
        )
        p = objects.project
        p.scm_update_on_launch = True
        p.scm_update_cache_timeout = 0
        p.scm_type = "git"
        p.scm_url = "http://github.com/ansible/ansible.git"
        p.save(skip_update=True)

        j = create_job(objects.job_template, dependencies_processed=False)

        with mock.patch('awx.main.models.unified_jobs.UnifiedJobTemplate.update'):
            DependencyManager().schedule()

        assert j.dependent_jobs.count() == 1
        pu = j.dependent_jobs.first()

        # Simulate the project update was canceled
        ProjectUpdate.objects.filter(pk=pu.pk).update(status='canceled', cancel_flag=True)
        pu.refresh_from_db()
        assert pu.status == 'canceled'

        # Run the task manager
        with mock.patch("awx.main.scheduler.TaskManager.start_task"):
            TaskManager().schedule()

        j.refresh_from_db()

        # process_job_dep_failures now handles "canceled" status
        assert j.status == 'failed'
        assert 'Previous Task Failed' in j.job_explanation

    def test_failed_dependency_fails_blocked_job(self, controlplane_instance_group, job_template_factory, mocker):
        """Verify that a FAILED dependency causes the blocked job to be
        failed. This was already working before the fix."""
        objects = job_template_factory(
            'jt',
            organization='org1',
            project='proj',
            inventory='inv',
            credential='cred',
        )
        p = objects.project
        p.scm_update_on_launch = True
        p.scm_update_cache_timeout = 0
        p.scm_type = "git"
        p.scm_url = "http://github.com/ansible/ansible.git"
        p.save(skip_update=True)

        j = create_job(objects.job_template, dependencies_processed=False)

        with mock.patch('awx.main.models.unified_jobs.UnifiedJobTemplate.update'):
            DependencyManager().schedule()

        assert j.dependent_jobs.count() == 1
        pu = j.dependent_jobs.first()

        # Mark the project update as failed
        ProjectUpdate.objects.filter(pk=pu.pk).update(status='failed')
        pu.refresh_from_db()
        assert pu.status == 'failed'

        # Run the task manager
        with mock.patch("awx.main.scheduler.TaskManager.start_task"):
            TaskManager().schedule()

        j.refresh_from_db()

        assert j.status == 'failed'
        assert 'Previous Task Failed' in j.job_explanation


@pytest.mark.django_db
class TestCancelWithApiAndTaskManager:
    """End-to-end tests using API cancel endpoint + task manager."""

    def test_cancel_job_via_api_cancels_dependency(self, controlplane_instance_group, job_template_factory, post, admin_user, mocker):
        """Cancel a pending job via the API cancel endpoint and verify the
        dependency project update is also canceled."""
        objects = job_template_factory(
            'jt',
            organization='org1',
            project='proj',
            inventory='inv',
            credential='cred',
        )
        p = objects.project
        p.scm_update_on_launch = True
        p.scm_update_cache_timeout = 0
        p.scm_type = "git"
        p.scm_url = "http://github.com/ansible/ansible.git"
        p.save(skip_update=True)

        j = create_job(objects.job_template, dependencies_processed=False)

        # Create dependency
        with mock.patch('awx.main.models.unified_jobs.UnifiedJobTemplate.update'):
            DependencyManager().schedule()

        assert j.dependent_jobs.count() == 1
        pu = j.dependent_jobs.first()

        # Simulate the project update running
        ProjectUpdate.objects.filter(pk=pu.pk).update(
            status='running',
            celery_task_id='fake-task-id',
            controller_node='test-node',
        )

        # Cancel the job via the API
        url = reverse('api:job_cancel', kwargs={'pk': j.pk})
        with mock.patch('awx.main.models.unified_jobs.UnifiedJob.cancel_dispatcher_process'):
            post(url, user=admin_user, expect=202)

        j.refresh_from_db()
        pu.refresh_from_db()

        assert j.cancel_flag is True
        # Cancel propagates to the dependency
        assert pu.cancel_flag is True

    def test_cancel_job_dep_canceled_then_task_manager_fails_job(self, controlplane_instance_group, job_template_factory, post, admin_user, mocker):
        """Cancel a job while its dependency project update is running.
        The cancel propagates to the dependency. When the task manager runs,
        it sees the canceled dependency and fails the job."""
        objects = job_template_factory(
            'jt',
            organization='org1',
            project='proj',
            inventory='inv',
            credential='cred',
        )
        p = objects.project
        p.scm_update_on_launch = True
        p.scm_update_cache_timeout = 0
        p.scm_type = "git"
        p.scm_url = "http://github.com/ansible/ansible.git"
        p.save(skip_update=True)

        j = create_job(objects.job_template, dependencies_processed=False)

        with mock.patch('awx.main.models.unified_jobs.UnifiedJobTemplate.update'):
            DependencyManager().schedule()

        assert j.dependent_jobs.count() == 1
        pu = j.dependent_jobs.first()

        # Project update is running
        ProjectUpdate.objects.filter(pk=pu.pk).update(
            status='running',
            celery_task_id='fake-task-id',
            controller_node='test-node',
        )

        # Cancel the job - this also cancels the dependency
        url = reverse('api:job_cancel', kwargs={'pk': j.pk})
        with mock.patch('awx.main.models.unified_jobs.UnifiedJob.cancel_dispatcher_process'):
            post(url, user=admin_user, expect=202)

        j.refresh_from_db()
        pu.refresh_from_db()
        assert j.cancel_flag is True
        assert pu.cancel_flag is True

        # Simulate the project update finishing as canceled
        ProjectUpdate.objects.filter(pk=pu.pk).update(status='canceled')

        # Run task manager - it sees canceled dep and fails the job
        with mock.patch("awx.main.scheduler.TaskManager.start_task") as mock_start:
            TaskManager().schedule()

        j.refresh_from_db()

        # The job is failed because its dependency was canceled
        assert j.status == 'failed'
        assert 'Previous Task Failed' in j.job_explanation
        assert not mock_start.called
