# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-02 14:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network_ui', '0002_auto_20180301_2039'),
    ]

    operations = [
        migrations.AlterField(
            model_name='codeundertest',
            name='commit_hash',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AlterField(
            model_name='databinding',
            name='field',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='databinding',
            name='table',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='datasheet',
            name='name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='datatype',
            name='type_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='device',
            name='device_type',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='device',
            name='name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='fsmtrace',
            name='from_state',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='fsmtrace',
            name='fsm_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='fsmtrace',
            name='message_type',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='fsmtrace',
            name='to_state',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='group',
            name='group_type',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='group',
            name='name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='interface',
            name='name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='link',
            name='name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='messagetype',
            name='name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='process',
            name='name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='process',
            name='process_type',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='result',
            name='name',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='stream',
            name='label',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='testcase',
            name='name',
            field=models.CharField(blank=True, max_length=200, verbose_name=b'TestCase'),
        ),
        migrations.AlterField(
            model_name='toolbox',
            name='name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='topology',
            name='name',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
