# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-04 21:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network_ui', '0003_auto_20180302_1401'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='databinding',
            name='data_type',
        ),
        migrations.RemoveField(
            model_name='databinding',
            name='sheet',
        ),
        migrations.RemoveField(
            model_name='datasheet',
            name='client',
        ),
        migrations.RemoveField(
            model_name='datasheet',
            name='topology',
        ),
        migrations.DeleteModel(
            name='DataBinding',
        ),
        migrations.DeleteModel(
            name='DataSheet',
        ),
        migrations.DeleteModel(
            name='DataType',
        ),
    ]
