# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-09 17:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('network_ui', '0028_coverage'),
    ]

    operations = [
        migrations.CreateModel(
            name='TopologySnapshot',
            fields=[
                ('topology_snapshot_id', models.AutoField(primary_key=True, serialize=False)),
                ('topology_id', models.IntegerField()),
                ('trace_session_id', models.IntegerField()),
                ('snapshot_data', models.TextField(verbose_name=b'TopologySnapshot')),
                ('order', models.IntegerField()),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='network_ui.Client')),
            ],
        ),
    ]
