# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-10 17:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('network_ui', '0029_topologysnapshot'),
    ]

    operations = [
        migrations.CreateModel(
            name='CodeUnderTest',
            fields=[
                ('code_under_test_id', models.AutoField(primary_key=True, serialize=False, verbose_name=b'CodeUnderTest')),
                ('version_x', models.IntegerField()),
                ('version_y', models.IntegerField()),
                ('version_z', models.IntegerField()),
                ('commits_since', models.IntegerField()),
                ('commit_hash', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Result',
            fields=[
                ('result_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='TestCase',
            fields=[
                ('test_case_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, verbose_name=b'TestCase')),
                ('test_case_data', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='TestResult',
            fields=[
                ('test_result_id', models.AutoField(primary_key=True, serialize=False)),
                ('time', models.DateTimeField()),
                ('code_under_test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='network_ui.CodeUnderTest')),
                ('result', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='network_ui.Result')),
                ('test_case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='network_ui.TestCase')),
            ],
        ),
        migrations.RemoveField(
            model_name='coverage',
            name='client',
        ),
        migrations.RemoveField(
            model_name='coverage',
            name='trace_session_id',
        ),
        migrations.AddField(
            model_name='coverage',
            name='test_result',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='network_ui.TestResult'),
            preserve_default=False,
        ),
    ]
