# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-12 21:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('network_ui', '0031_auto_20180110_1752'),
    ]

    operations = [
        migrations.AddField(
            model_name='testresult',
            name='client',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='network_ui.Client'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='testresult',
            name='id',
            field=models.IntegerField(default=0),
        ),
    ]
