# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-13 17:25
from __future__ import unicode_literals

from django.db import migrations
import json

def add_load_test_case(apps, schema_editor):

    TestCase = apps.get_model('network_ui', 'TestCase')
    TestCase.objects.get_or_create(name="Load", test_case_data=json.dumps(dict(runnable=False)))


class Migration(migrations.Migration):

    dependencies = [
        ('network_ui', '0033_auto_20180112_2202'),
    ]

    operations = [
        migrations.RunPython(
            code=add_load_test_case,
        ),
    ]
