# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-23 00:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network_ui', '0034_auto_20180113_1725'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='inventory_group_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='topology',
            name='group_id_seq',
            field=models.IntegerField(default=0),
        ),
    ]
