# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-06 18:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('network_ui', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CodeUnderTest',
            fields=[
                ('code_under_test_id', models.AutoField(primary_key=True, serialize=False, verbose_name=b'CodeUnderTest')),
                ('version_x', models.IntegerField()),
                ('version_y', models.IntegerField()),
                ('version_z', models.IntegerField()),
                ('commits_since', models.IntegerField()),
                ('commit_hash', models.CharField(blank=True, max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Coverage',
            fields=[
                ('coverage_id', models.AutoField(primary_key=True, serialize=False)),
                ('coverage_data', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='EventTrace',
            fields=[
                ('event_trace_id', models.AutoField(primary_key=True, serialize=False)),
                ('trace_session_id', models.IntegerField(default=0)),
                ('event_data', models.TextField()),
                ('message_id', models.IntegerField()),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='network_ui.Client')),
            ],
        ),
        migrations.CreateModel(
            name='FSMTrace',
            fields=[
                ('fsm_trace_id', models.AutoField(primary_key=True, serialize=False)),
                ('fsm_name', models.CharField(blank=True, max_length=200)),
                ('from_state', models.CharField(blank=True, max_length=200)),
                ('to_state', models.CharField(blank=True, max_length=200)),
                ('message_type', models.CharField(blank=True, max_length=200)),
                ('trace_session_id', models.IntegerField(default=0)),
                ('order', models.IntegerField(default=0)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='network_ui.Client')),
            ],
        ),
        migrations.CreateModel(
            name='Result',
            fields=[
                ('result_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='TestCase',
            fields=[
                ('test_case_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=200, verbose_name=b'TestCase')),
                ('test_case_data', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='TestResult',
            fields=[
                ('test_result_id', models.AutoField(primary_key=True, serialize=False)),
                ('time', models.DateTimeField()),
                ('id', models.IntegerField(default=0)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='network_ui.Client')),
                ('code_under_test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='network_ui_test.CodeUnderTest')),
                ('result', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='network_ui_test.Result')),
                ('test_case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='network_ui_test.TestCase')),
            ],
        ),
        migrations.CreateModel(
            name='TopologySnapshot',
            fields=[
                ('topology_snapshot_id', models.AutoField(primary_key=True, serialize=False)),
                ('topology_id', models.IntegerField()),
                ('trace_session_id', models.IntegerField()),
                ('snapshot_data', models.TextField(verbose_name=b'TopologySnapshot')),
                ('order', models.IntegerField()),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='network_ui.Client')),
            ],
        ),
        migrations.AddField(
            model_name='coverage',
            name='test_result',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='network_ui_test.TestResult'),
        ),
    ]
