# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-06 22:43
from __future__ import unicode_literals

from django.db import migrations


results = ['passed', 'failed', 'errored', 'skipped',
           'aborted', 'not run', 'blocked']


def populate_result_types(apps, schema_editor):

    Result = apps.get_model('network_ui_test', 'Result')
    for result in results:
        Result.objects.get_or_create(name=result)


class Migration(migrations.Migration):

    dependencies = [
        ('network_ui_test', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(
            code=populate_result_types,
        ),
    ]
