{
 "title": "PostgreSQL Statement Statistics",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Statement Statistics",
   "type": "table",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT s.mean_time as \"mean_exec_time_ms\",\n       s.max_time as \"max_exec_time_ms\",\n       s.calls,\n       s.query\n  FROM pg_stat_statements s\n WHERE s.userid != 'db_monitor'::regrole\n ORDER BY 1 desc"
    }
   ]
  },
  {
   "title": "Query State",
   "type": "table",
   "gridPos": { "h": 6, "w": 5, "x": 0, "y": 12 },
   "targets": [
    {
     "rawSql": "select x.state, \n       x.\"count\",\n       y.\"total\",\n       (x.\"count\"::numeric(10,4) / y.\"total\"::numeric(10,4))::numeric(10,4) as \"pct\"\n  from (\n         select \"state\",\n                count(*) as \"count\"\n           from pg_stat_activity\n          where usename is not null\n            and usename != 'db_monitor'\n            and state is not null\n          group \n             by \"state\"\n       ) as x\n cross\n  join (\n         select count(*) as \"total\"\n           from pg_stat_activity\n          where usename is not null \n            and usename != 'dbmonitor'\n            and state is not null\n       ) as y\n order \n    by x.\"state\";"
    }
   ]
  },
  {
   "title": "Active Query Times",
   "type": "table",
   "gridPos": { "h": 7, "w": 19, "x": 5, "y": 12 },
   "targets": [
    {
     "rawSql": "select extract(epoch from (now() - query_start))::numeric(12,4) as \"elapsed\",\n       wait_event_type as \"wait_type\",\n       query\n  from pg_stat_activity\n where state = 'active'\n   and usename != 'db_monitor'\n order \n    by 1 desc;\n"
    }
   ]
  },
  {
   "title": "Query Wait Types",
   "type": "table",
   "gridPos": { "h": 6, "w": 5, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "rawSql": "select x.wait_event_type, \n       x.\"count\",\n       y.\"total\",\n       case when y.\"total\" = 0 \n                 then 0.0::numeric(10,4) \n            else (x.\"count\"::numeric(10,4) / y.\"total\"::numeric(10,4))::numeric(10,4) \n       end::numeric(10,4) as \"pct\"\n  from (\n         select \"wait_event_type\",\n                count(*) as \"count\"\n           from pg_stat_activity\n          where usename is not null \n            and usename != 'db_monitor'\n            and wait_event_type is not null\n            and state != 'idle'\n          group \n             by \"wait_event_type\"\n       ) as x\n cross\n  join (\n         select count(*) as \"total\"\n           from pg_stat_activity\n          where usename is not null \n            and usename != 'dbmonitor'\n            and wait_event_type is not null\n            and state != 'idle'\n       ) as y\n order \n    by x.\"wait_event_type\";\n"
    }
   ]
  },
  {
   "title": "Query Wait Detail",
   "type": "table",
   "gridPos": { "h": 5, "w": 19, "x": 5, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "rawSql": "select wait_event_type,\n       wait_event,\n       query\n  from pg_stat_activity\n where usename is not null\n   and usename != 'db_monitor'\n   and state = 'active'\n   and wait_event_type is not null;\n"
    }
   ]
  }
 ]
}