---
apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  name: awx-atf-tests-pull-request
  annotations:
    build.appstudio.openshift.io/repo: https://github.com/{{repo_owner}}/{{repo_name}}?rev={{revision}}
    build.appstudio.redhat.com/commit_sha: '{{revision}}'
    build.appstudio.redhat.com/pull_request_number: '{{pull_request_number}}'
    build.appstudio.redhat.com/target_branch: '{{target_branch}}'
    pipelinesascode.tekton.dev/cancel-in-progress: 'true'
    pipelinesascode.tekton.dev/max-keep-runs: "3"
    pipelinesascode.tekton.dev/on-comment: "^/run-atf-tests$"
    pipelinesascode.tekton.dev/target-namespace: ansible-ci-tenant
  labels:
    appstudio.openshift.io/application: '{{repo_owner}}'
    appstudio.openshift.io/component: '{{repo_owner}}-{{repo_name}}'
    pipelines.appstudio.openshift.io/type: build
spec:
  timeouts:
    pipeline: "8h"
    tasks: "7h"
    finally: "1h"
  pipelineRef:
    resolver: bundles
    params:
      - name: name
        value: aap-api-tests
      - name: bundle
        value: quay.io/aap-ci/tekton-catalog/pipeline/test/aap-api-tests:0.1@sha256:33add0295c6cb0f0960d5b030b4d1ff556221447ef45cb33c82ccae7f605f03a
      - name: kind
        value: pipeline
      - name: secret
        value: quay-aap-ci-viewer

  taskRunTemplate:
    serviceAccountName: konflux-integration-runner

  params:
    - name: git-url
      value: "{{source_url}}"
    - name: pipeline-github-org
      value: "{{repo_owner}}"
    - name: pipeline-github-repo
      value: "{{repo_name}}"
    - name: pipeline-github-target-branch
      value: '{{target_branch}}'
    - name: pipeline-github-pr-revision
      value: "{{revision}}"
    - name: pipeline-github-pr-number
      value: "{{pull_request_number}}"
    - name: aap-dev-component-source-name
      value: "controller"
    - name: pytest-number-of-parallel-processes
      value: "6"

  workspaces:
    - name: workspace
      volumeClaimTemplate:
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 1Gi
