[tox]
distshare = {homedir}/.tox/distshare
envlist =
    lint,
    test
skip_missing_interpreters = true
# recreate = true
# skipsdist = true

[testenv]
basepython = python3.12
setenv =
    PYTHONPATH = {toxinidir}:{env:PYTHONPATH:}:.
deps =
    websocket-client
    coverage
    mock
    pytest
    pytest-mock

commands =
    coverage run --parallel --source awxkit -m pytest -c pytest.ini test --doctest-glob='*.md' --junit-xml=report.xml {posargs}
    coverage combine
    coverage xml

[testenv:lint]
deps =
    {[testenv]deps}
    ruff
commands =
    ruff check awxkit
    - coverage erase

[testenv:coveralls]
commands=
    - coverage combine
    - coverage report -m
    - coveralls

[pytest]
addopts = -v --tb=native
testpaths = test
python_files = test_*.py

filterwarnings =
  error

junit_family=xunit2
