FROM centos:8

RUN dnf -y update && dnf -y install epel-release && \
    dnf install -y bzip2 \
    gcc-c++ \
    gettext \
    git \
    make \
    nodejs \
    python3 \
    python3-setuptools

# Use the distro provided npm to bootstrap our required version of node
RUN npm install -g n && n 14.15.1 && dnf remove -y nodejs

RUN mkdir -p /.npm && chmod g+rwx /.npm

ENV PATH=/usr/local/n/versions/node/14.15.1/bin:$PATH

WORKDIR "/awx"

CMD ["make", "sdist"]
