FROM centos:8

RUN dnf -y update && dnf -y install epel-release && \
    dnf install -y bzip2 \
    gcc-c++ \
    gettext \
    git \
    make \
    nodejs \
    python3 \
    python3-setuptools

# Use the distro provided npm to bootstrap our required version of node
RUN npm install -g n && n 10.15.0 && dnf remove -y nodejs

ENV PATH=/usr/local/n/versions/node/10.15.0/bin:$PATH

WORKDIR "/awx"

ENTRYPOINT ["/bin/bash", "-c"]
CMD ["make sdist"]
