---
collections:
  - source: ./awx_collection
    type: dir
  - name: flowerysong.hvault
    source: https://github.com/flowerysong/ansible-flowerysong.hvault.git
    type: git
    version: "v0.3.0"
  - name: community.docker
    source: https://github.com/ansible-collections/community.docker.git
    type: git
    version: "5.0.5"
