---
name: CalVer Tagging
on:
  workflow_dispatch:
  push:
    branches:
jobs:
  tag:
    environment: CALVER
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: Create git tag
        uses: Digital-Udvikling/actions-calver@v0.4.0
        with: ${{ secrets.SUPERSECRET }}
