---
name: CalVer Tagging
on:
  workflow_dispatch:
  push:
    branches:
jobs:
  tag:
    permissions:
      contents: write
    runs-on: 
      group: linux
    steps:
      - name: Create git tag
        uses: Digital-Udvikling/actions-calver@v0.4.0
        with: ${{ secrets.GITHUB_TOKEN }}
