#!/bin/sh

case $1 in
   config)
        cat <<'EOM'
graph_title Postmaster Processes
graph_vlabel num processes
graph_category tower
postmaster.label Postmaster Processes
EOM
        exit 0;;
esac

printf "postmaster.value "
ps ax | grep postmaster | grep -v grep | wc -l
printf "\n"
