#!/bin/sh

case $1 in
   config)
        cat <<'EOM'
graph_title Redis Processes
graph_vlabel num processes
graph_category tower
redis.label Redis Processes
EOM
        exit 0;;
esac

printf "redis.value "
ps ax | grep redis | grep -v grep | wc -l
printf "\n"
